### ISSUE TITLE
ERROR WHEN EXECUTING VMAMBA_CHECKS

### ISSUE THREAD

**Issue by gecgomes** [MzeroMiko/VMamba#110]
```shell
Traceback (most recent call last):
  File "VMamba/classification/models/vmamba_checks.py", line 581, in <module>
    CHECKS.check_vssblock()
  File "VMamba/classification/models/vmamba_checks.py", line 343, in check_vssblock
    ms = triton.testing.do_bench(fn, warmup=100)
  File "/cfs/home/u021414/Environments/vmamba/lib64/python3.10/site-packages/triton/testing.py", line 102, in do_bench
    fn()
  File "VMamba/classification/models/vmamba_checks.py", line 342, in <lambda>
    fn = lambda :vb(inp)
  File "/cfs/home/u021414/Environments/vmamba/lib64/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/cfs/home/u021414/Environments/vmamba/lib64/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "VMamba/classification/models/vmamba.py", line 1381, in forward
    return self._forward(input)
  File "VMamba/classification/models/vmamba.py", line 1369, in _forward
    x = input + self.drop_path(self.op(self.norm(input)))
  File "/cfs/home/u021414/Environments/vmamba/lib64/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/cfs/home/u021414/Environments/vmamba/lib64/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "VMamba/classification/models/vmamba.py", line 1161, in forwardv2
    y = self.forward_core(x)
  File "VMamba/classification/models/vmamba.py", line 1117, in forward_corev2
    ys: torch.Tensor = selective_scan(
  File "VMamba/classification/models/vmamba.py", line 1088, in selective_scan
    return SelectiveScan.apply(u, delta, A, B, C, D, delta_bias, delta_softplus, nrows, backnrows, ssoflex)
  File "Environments/vmamba/lib64/python3.10/site-packages/torch/autograd/function.py", line 553, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "Environments/vmamba/lib64/python3.10/site-packages/torch/cuda/amp/autocast_mode.py", line 115, in decorate_fwd
    return fwd(*args, **kwargs)
  File "VMamba/classification/models/vmamba.py", line 281, in forward
    out, x, *rest = selective_scan_cuda_core.fwd(u, delta, A, B, C, D, delta_bias, delta_softplus, 1)
RuntimeError: memory format option is only supported by strided tensors
```

**Comment by MzeroMiko** [comment]
Sorry, I myself didn't encounter any error or warning in running `CHECKS.check_vssblock()`, so I have no idea what happened in your environment.

**Comment by gecgomes** [comment]
My cuda version is 12.3, do you think that is the problem?

**Comment by vkxuds** [comment]
> My cuda version is 12.3, do you think that is the problem?

Hello, I encountered the same issue. Have you solved it?
