### ISSUE TITLE
CUDA version requirements

### ISSUE THREAD

**Issue by bregesyn** [MzeroMiko/VMamba#134]
hello！

First of all, I'd like to express my sincere thanks for your great work on the VMamba project. This project has been of great help to my research and work, for which I am very appreciative and grateful.

While trying to install and use the project, I noticed that the installation process requires a CUDA version of at least 11.6. Due to hardware and other dependency limitations, the CUDA version installed in my environment can only be up to 11.4.

Therefore, I would like to ask a few questions:

1. Does the project absolutely require CUDA 11.6 and above to run properly?
2. Do you have a suggested solution or alternative for environments that only support CUDA 11.4? For example, is it possible to modify the configuration or source code to be compatible with CUDA 11.4?
3. If the code needs to be adjusted to support CUDA 11.4, can you provide some advice or guidance to help me achieve this?

I'd really like to have this work successfully in my environment. Any advice and help on how to resolve this compatibility issue would be extremely valuable and appreciated.

Very much looking forward to your reply！

Best wishes！

**Comment by MzeroMiko** [comment]
@bregesyn If you want to forcefully run the code in cuda11.4, I have prepared the code `kernels/selective_scan/csrc/selective_scan/cub_extra.cuh` for you, and you only need to do is  `CUDA_HOME=/usr/local/cuda-11.4/ pip install .` in directory `kernels/selective_scan/`.

If there's any warning or errors, do not hesitate to show me, and I'll help you fix that.

**Comment by wenqiuL** [comment]
> @bregesyn If you want to forcefully run the code in cuda11.4, I have prepared the code `kernels/selective_scan/csrc/selective_scan/cub_extra.cuh` for you, and you only need to do is `CUDA_HOME=/usr/local/cuda-11.4/ pip install .` in directory `kernels/selective_scan/`.
> 
> If there's any warning or errors, do not hesitate to show me, and I'll help you fix that.
> 
> If you are using python3.7, you need to add `cached_property = lambda func: property(lru_cache()(func))` into `functools.py` to use triton.
Hello author, I have also encountered a similar problem. Can you help me solve it?, Thank you.The installed versions of Python and PyTorch are shown in the picture, but there was still an error during the installation of selective_stcan

(vmamba) D:\X-ray_detection\VMamba-main\VMamba-main\kernels\selective_scan>pip install numpy   
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting numpy
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/16/9f/1fcb7fdb6ec988052b42c7f4ed6d92d89c541d640f8f39f01bf141d17426/numpy-2.0.1-cp310-cp310-win_amd64.whl (16.6 MB)
Installing collected packages: numpy
Successfully installed numpy-2.0.1

(vmamba) D:\X-ray_detection\VMamba-main\VMamba-main\kernels\selective_scan>pip install .                                                                                
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Processing d:\x-ray_detection\vmamba-main\vmamba-main\kernels\selective_scan
  Preparing metadata (setup.py) ... done
Requirement already satisfied: torch in d:\anaconda\envs\vmamba\lib\site-packages (from selective_scan==0.0.2) (2.1.0+cu118)
Requirement already satisfied: packaging in d:\anaconda\envs\vmamba\lib\site-packages (from selective_scan==0.0.2) (24.1)
Collecting ninja (from selective_scan==0.0.2)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/b6/2f/a3bc50fa63fc4fe9348e15b53dc8c87febfd4e0c660fcf250c4b19a3aa3b/ninja-1.11.1.1-py2.py3-none-win_amd64.whl (312 kB)
Collecting einops (from selective_scan==0.0.2)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/44/5a/f0b9ad6c0a9017e62d4735daaeb11ba3b6c009d69a26141b258cd37b5588/einops-0.8.0-py3-none-any.whl (43 kB)
Requirement already satisfied: filelock in d:\anaconda\envs\vmamba\lib\site-packages (from torch->selective_scan==0.0.2) (3.15.4)
Requirement already satisfied: typing-extensions in d:\anaconda\envs\vmamba\lib\site-packages (from torch->selective_scan==0.0.2) (4.12.2)
Requirement already satisfied: sympy in d:\anaconda\envs\vmamba\lib\site-packages (from torch->selective_scan==0.0.2) (1.13.1)
Requirement already satisfied: networkx in d:\anaconda\envs\vmamba\lib\site-packages (from torch->selective_scan==0.0.2) (3.3)
Requirement already satisfied: jinja2 in d:\anaconda\envs\vmamba\lib\site-packages (from torch->selective_scan==0.0.2) (3.1.4)
Requirement already satisfied: fsspec in d:\anaconda\envs\vmamba\lib\site-packages (from torch->selective_scan==0.0.2) (2024.6.1)
Requirement already satisfied: MarkupSafe>=2.0 in d:\anaconda\envs\vmamba\lib\site-packages (from jinja2->torch->selective_scan==0.0.2) (2.1.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in d:\anaconda\envs\vmamba\lib\site-packages (from sympy->torch->selective_scan==0.0.2) (1.3.0)
Building wheels for collected packages: selective_scan
  Building wheel for selective_scan (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [74 lines of output]

      A module that was compiled using NumPy 1.x cannot be run in
      NumPy 2.0.1 as it may crash. To support both 1.x and 2.x
      versions of NumPy, modules must be compiled with NumPy 2.0.
      Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

      If you are a user of the module, the easiest solution will be to
      downgrade to 'numpy<2' or try to upgrade the affected module.
      We expect that some modules will need time to support NumPy 2.

      Traceback (most recent call last):  File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "D:\X-ray_detection\VMamba-main\VMamba-main\kernels\selective_scan\setup.py", line 17, in <module>
          import torch
        File "D:\anaconda\envs\vmamba\lib\site-packages\torch\__init__.py", line 1382, in <module>
          from .functional import *  # noqa: F403
        File "D:\anaconda\envs\vmamba\lib\site-packages\torch\functional.py", line 7, in <module>
          import torch.nn.functional as F
        File "D:\anaconda\envs\vmamba\lib\site-packages\torch\nn\__init__.py", line 1, in <module>
          from .modules import *  # noqa: F403
        File "D:\anaconda\envs\vmamba\lib\site-packages\torch\nn\modules\__init__.py", line 35, in <module>
          from .transformer import TransformerEncoder, TransformerDecoder, \
        File "D:\anaconda\envs\vmamba\lib\site-packages\torch\nn\modules\transformer.py", line 20, in <module>
          device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
      D:\anaconda\envs\vmamba\lib\site-packages\torch\nn\modules\transformer.py:20: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:84.)
        device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),


      torch.__version__  = 2.1.0+cu118




      CUDA_HOME = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8


      CUDA version:  11.8
      running bdist_wheel
      D:\anaconda\envs\vmamba\lib\site-packages\torch\utils\cpp_extension.py:502: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
        warnings.warn(msg.format('we could not find ninja.'))
      running build
      running build_ext
      D:\anaconda\envs\vmamba\lib\site-packages\torch\utils\cpp_extension.py:383: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
        warnings.warn(f'Error checking compiler version for {compiler}: {error}')
      building 'selective_scan_cuda_oflex' extension
      creating build
      creating build\temp.win-amd64-cpython-310
      creating build\temp.win-amd64-cpython-310\Release
      creating build\temp.win-amd64-cpython-310\Release\csrc
      creating build\temp.win-amd64-cpython-310\Release\csrc\selective_scan
      creating build\temp.win-amd64-cpython-310\Release\csrc\selective_scan\cusoflex
      "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvcc" -c csrc/selective_scan/cusoflex/selective_scan_core_bwd.cu -o build\temp.win-amd64-cpython-310\Release\csrc/selective_scan/cusoflex/selective_scan_core
_bwd.obj -ID:\X-ray_detection\VMamba-main\VMamba-main\kernels\selective_scan\csrc\selective_scan -ID:\anaconda\envs\vmamba\lib\site-packages\torch\include -ID:\anaconda\envs\vmamba\lib\site-packages\torch\include\torch\csrc\a
pi\include -ID:\anaconda\envs\vmamba\lib\site-packages\torch\include\TH -ID:\anaconda\envs\vmamba\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include" -ID:\anaconda\envs\vma
mba\include -ID:\anaconda\envs\vmamba\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\
ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.
22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cp
pwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=f
ield_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4068 -Xcompiler /wd4067 -Xcompiler /wd4624 -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xc
ompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relax
ed-constexpr -O3 -std=c++17 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_BFLOAT16_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -U__CUDA_NO_BFLOAT162_OPERATORS__ -U__CUDA_NO_BFLOAT162_CONVERSIONS__
 --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --ptxas-options=-v -lineinfo -gencode arch=compute_70,code=sm_70 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_90,code=sm_90 --threads 4 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=selective_scan_cuda_oflex -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++17 --use-local-env
      selective_scan_core_bwd.cu
      cl: 命令行 warning D9025 :正在重写“/D__CUDA_NO_HALF_OPERATORS__”(用“/U__CUDA_NO_HALF_OPERATORS__”)
      cl: 命令行 warning D9025 :正在重写“/D__CUDA_NO_HALF_CONVERSIONS__”(用“/U__CUDA_NO_HALF_CONVERSIONS__”)
      cl: 命令行 warning D9025 :正在重写“/D__CUDA_NO_BFLOAT16_CONVERSIONS__”(用“/U__CUDA_NO_BFLOAT16_CONVERSIONS__”)
      selective_scan_core_bwd.cu
      C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include\crt/host_config.h(153): fatal error C1189: #error:  -- unsupported Microsoft Visual Studio version! Only the versions between 2017 and 2022 (inclusive) ar
e supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
      cl: 命令行 warning D9025 :正在重写“/D__CUDA_NO_HALF_OPERATORS__”(用“/U__CUDA_NO_HALF_OPERATORS__”)
      cl: 命令行 warning D9025 :正在重写“/D__CUDA_NO_HALF_CONVERSIONS__”(用“/U__CUDA_NO_HALF_CONVERSIONS__”)
      cl: 命令行 warning D9025 :正在重写“/D__CUDA_NO_BFLOAT16_CONVERSIONS__”(用“/U__CUDA_NO_BFLOAT16_CONVERSIONS__”)
      selective_scan_core_bwd.cu
      C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include\crt/host_config.h(153): fatal error C1189: #error:  -- unsupported Microsoft Visual Studio version! Only the versions between 2017 and 2022 (inclusive) ar
e supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
      cl: 命令行 warning D9025 :正在重写“/D__CUDA_NO_HALF_OPERATORS__”(用“/U__CUDA_NO_HALF_OPERATORS__”)
      cl: 命令行 warning D9025 :正在重写“/D__CUDA_NO_HALF_CONVERSIONS__”(用“/U__CUDA_NO_HALF_CONVERSIONS__”)
      cl: 命令行 warning D9025 :正在重写“/D__CUDA_NO_BFLOAT16_CONVERSIONS__”(用“/U__CUDA_NO_BFLOAT16_CONVERSIONS__”)
      selective_scan_core_bwd.cu
      C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include\crt/host_config.h(153): fatal error C1189: #error:  -- unsupported Microsoft Visual Studio version! Only the versions between 2017 and 2022 (inclusive) ar
e supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
      cl: 命令行 warning D9025 :正在重写“/D__CUDA_NO_HALF_OPERATORS__”(用“/U__CUDA_NO_HALF_OPERATORS__”)
      cl: 命令行 warning D9025 :正在重写“/D__CUDA_NO_HALF_CONVERSIONS__”(用“/U__CUDA_NO_HALF_CONVERSIONS__”)
      cl: 命令行 warning D9025 :正在重写“/D__CUDA_NO_BFLOAT16_CONVERSIONS__”(用“/U__CUDA_NO_BFLOAT16_CONVERSIONS__”)
      selective_scan_core_bwd.cu
      C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include\crt/host_config.h(153): fatal error C1189: #error:  -- unsupported Microsoft Visual Studio version! Only the versions between 2017 and 2022 (inclusive) ar
e supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
      error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.8\\bin\\nvcc.exe' failed with exit code 4294967295
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for selective_scan
  Running setup.py clean for selective_scan
Failed to build selective_scan
ERROR: Could not build wheels for selective_scan, which is required to install pyproject.toml-based projects
![3ebb4532-cd3d-45c8-a766-acc648a9fa80](https://github.com/user-attachments/assets/16e7a372-4a4d-4ee4-9a73-4d8b8d5a1a42)
