### ISSUE TITLE
Could not build wheels for selective_scan, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by XiaoBaiHhy** [MzeroMiko/VMamba#162]
Hello, I encountered the following error while trying to install. Can you try to resolve it?
Processing /home/hhy/下载/VMamba-main/kernels/selective_scan
  Preparing metadata (setup.py) ... done
Requirement already satisfied: torch in /home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages (from selective_scan==0.0.2) (2.1.1+cu118)
Requirement already satisfied: packaging in /home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages (from selective_scan==0.0.2) (23.2)
Requirement already satisfied: ninja in /home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages (from selective_scan==0.0.2) (1.11.1.1)
Requirement already satisfied: einops in /home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages (from selective_scan==0.0.2) (0.7.0)
Requirement already satisfied: filelock in /home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages (from torch->selective_scan==0.0.2) (3.9.0)
Requirement already satisfied: typing-extensions in /home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages (from torch->selective_scan==0.0.2) (4.8.0)
Requirement already satisfied: sympy in /home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages (from torch->selective_scan==0.0.2) (1.12)
Requirement already satisfied: networkx in /home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages (from torch->selective_scan==0.0.2) (3.2.1)
Requirement already satisfied: jinja2 in /home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages (from torch->selective_scan==0.0.2) (3.1.2)
Requirement already satisfied: fsspec in /home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages (from torch->selective_scan==0.0.2) (2024.3.1)
Requirement already satisfied: triton==2.1.0 in /home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages (from torch->selective_scan==0.0.2) (2.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages (from jinja2->torch->selective_scan==0.0.2) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in /home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages (from sympy->torch->selective_scan==0.0.2) (1.3.0)
Building wheels for collected packages: selective_scan
  Building wheel for selective_scan (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [118 lines of output]
      
      
      torch.__version__  = 2.1.1+cu118
      
      
      
      
      CUDA_HOME = /home/hhy/anaconda3/envs/mamba
      
      
      running bdist_wheel
      running build
      running build_ext
      /home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/utils/cpp_extension.py:424: UserWarning: There are no g++ version bounds defined for CUDA version 11.8
        warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
      building 'selective_scan_cuda_core' extension
      creating /home/hhy/下载/VMamba-main/kernels/selective_scan/build
      creating /home/hhy/下载/VMamba-main/kernels/selective_scan/build/temp.linux-x86_64-cpython-310
      creating /home/hhy/下载/VMamba-main/kernels/selective_scan/build/temp.linux-x86_64-cpython-310/csrc
      creating /home/hhy/下载/VMamba-main/kernels/selective_scan/build/temp.linux-x86_64-cpython-310/csrc/selective_scan
      creating /home/hhy/下载/VMamba-main/kernels/selective_scan/build/temp.linux-x86_64-cpython-310/csrc/selective_scan/cus
      Emitting ninja build file /home/hhy/下载/VMamba-main/kernels/selective_scan/build/temp.linux-x86_64-cpython-310/build.ninja...
      Compiling objects...
      Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
      [1/3] c++ -MMD -MF '/home/hhy/下载/VMamba-main/kernels/selective_scan/build/temp.linux-x86_64-cpython-310/csrc/selective_scan/cus/selective_scan.o'.d -pthread -B /home/hhy/anaconda3/envs/mamba/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/hhy/anaconda3/envs/mamba/include -fPIC -O2 -isystem /home/hhy/anaconda3/envs/mamba/include -fPIC '-I/home/hhy/下载/VMamba-main/kernels/selective_scan/csrc/selective_scan' -I/home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include -I/home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include/TH -I/home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include/THC -I/home/hhy/anaconda3/envs/mamba/include -I/home/hhy/anaconda3/envs/mamba/include/python3.10 -c -c '/home/hhy/下载/VMamba-main/kernels/selective_scan/csrc/selective_scan/cus/selective_scan.cpp' -o '/home/hhy/下载/VMamba-main/kernels/selective_scan/build/temp.linux-x86_64-cpython-310/csrc/selective_scan/cus/selective_scan.o' -O3 -std=c++17 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=selective_scan_cuda_core -D_GLIBCXX_USE_CXX11_ABI=0
      FAILED: /home/hhy/下载/VMamba-main/kernels/selective_scan/build/temp.linux-x86_64-cpython-310/csrc/selective_scan/cus/selective_scan.o
      c++ -MMD -MF '/home/hhy/下载/VMamba-main/kernels/selective_scan/build/temp.linux-x86_64-cpython-310/csrc/selective_scan/cus/selective_scan.o'.d -pthread -B /home/hhy/anaconda3/envs/mamba/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/hhy/anaconda3/envs/mamba/include -fPIC -O2 -isystem /home/hhy/anaconda3/envs/mamba/include -fPIC '-I/home/hhy/下载/VMamba-main/kernels/selective_scan/csrc/selective_scan' -I/home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include -I/home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include/TH -I/home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include/THC -I/home/hhy/anaconda3/envs/mamba/include -I/home/hhy/anaconda3/envs/mamba/include/python3.10 -c -c '/home/hhy/下载/VMamba-main/kernels/selective_scan/csrc/selective_scan/cus/selective_scan.cpp' -o '/home/hhy/下载/VMamba-main/kernels/selective_scan/build/temp.linux-x86_64-cpython-310/csrc/selective_scan/cus/selective_scan.o' -O3 -std=c++17 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=selective_scan_cuda_core -D_GLIBCXX_USE_CXX11_ABI=0
      In file included from /home/hhy/下载/VMamba-main/kernels/selective_scan/csrc/selective_scan/cus/selective_scan.cpp:5:
      /home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include/ATen/cuda/CUDAContext.h:5:10: fatal error: cuda_runtime_api.h: 没有那个文件或目录
          5 | #include <cuda_runtime_api.h>
            |          ^~~~~~~~~~~~~~~~~~~~
      compilation terminated.
      [2/3] /home/hhy/anaconda3/envs/mamba/bin/nvcc  '-I/home/hhy/下载/VMamba-main/kernels/selective_scan/csrc/selective_scan' -I/home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include -I/home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include/TH -I/home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include/THC -I/home/hhy/anaconda3/envs/mamba/include -I/home/hhy/anaconda3/envs/mamba/include/python3.10 -c -c '/home/hhy/下载/VMamba-main/kernels/selective_scan/csrc/selective_scan/cus/selective_scan_core_fwd.cu' -o '/home/hhy/下载/VMamba-main/kernels/selective_scan/build/temp.linux-x86_64-cpython-310/csrc/selective_scan/cus/selective_scan_core_fwd.o' -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -std=c++17 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_BFLOAT16_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -U__CUDA_NO_BFLOAT162_OPERATORS__ -U__CUDA_NO_BFLOAT162_CONVERSIONS__ --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --ptxas-options=-v -lineinfo -gencode arch=compute_70,code=sm_70 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_90,code=sm_90 --threads 4 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=selective_scan_cuda_core -D_GLIBCXX_USE_CXX11_ABI=0
      FAILED: /home/hhy/下载/VMamba-main/kernels/selective_scan/build/temp.linux-x86_64-cpython-310/csrc/selective_scan/cus/selective_scan_core_fwd.o
      /home/hhy/anaconda3/envs/mamba/bin/nvcc  '-I/home/hhy/下载/VMamba-main/kernels/selective_scan/csrc/selective_scan' -I/home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include -I/home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include/TH -I/home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include/THC -I/home/hhy/anaconda3/envs/mamba/include -I/home/hhy/anaconda3/envs/mamba/include/python3.10 -c -c '/home/hhy/下载/VMamba-main/kernels/selective_scan/csrc/selective_scan/cus/selective_scan_core_fwd.cu' -o '/home/hhy/下载/VMamba-main/kernels/selective_scan/build/temp.linux-x86_64-cpython-310/csrc/selective_scan/cus/selective_scan_core_fwd.o' -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -std=c++17 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_BFLOAT16_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -U__CUDA_NO_BFLOAT162_OPERATORS__ -U__CUDA_NO_BFLOAT162_CONVERSIONS__ --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --ptxas-options=-v -lineinfo -gencode arch=compute_70,code=sm_70 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_90,code=sm_90 --threads 4 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=selective_scan_cuda_core -D_GLIBCXX_USE_CXX11_ABI=0
      cc1plus: fatal error: cuda_runtime.h: 没有那个文件或目录
      compilation terminated.
      cc1plus: fatal error: cuda_runtime.h: 没有那个文件或目录
      compilation terminated.
      cc1plus: fatal error: cuda_runtime.h: 没有那个文件或目录
      compilation terminated.
      cc1plus: fatal error: cuda_runtime.h: 没有那个文件或目录
      compilation terminated.
      [3/3] /home/hhy/anaconda3/envs/mamba/bin/nvcc  '-I/home/hhy/下载/VMamba-main/kernels/selective_scan/csrc/selective_scan' -I/home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include -I/home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include/TH -I/home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include/THC -I/home/hhy/anaconda3/envs/mamba/include -I/home/hhy/anaconda3/envs/mamba/include/python3.10 -c -c '/home/hhy/下载/VMamba-main/kernels/selective_scan/csrc/selective_scan/cus/selective_scan_core_bwd.cu' -o '/home/hhy/下载/VMamba-main/kernels/selective_scan/build/temp.linux-x86_64-cpython-310/csrc/selective_scan/cus/selective_scan_core_bwd.o' -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -std=c++17 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_BFLOAT16_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -U__CUDA_NO_BFLOAT162_OPERATORS__ -U__CUDA_NO_BFLOAT162_CONVERSIONS__ --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --ptxas-options=-v -lineinfo -gencode arch=compute_70,code=sm_70 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_90,code=sm_90 --threads 4 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=selective_scan_cuda_core -D_GLIBCXX_USE_CXX11_ABI=0
      FAILED: /home/hhy/下载/VMamba-main/kernels/selective_scan/build/temp.linux-x86_64-cpython-310/csrc/selective_scan/cus/selective_scan_core_bwd.o
      /home/hhy/anaconda3/envs/mamba/bin/nvcc  '-I/home/hhy/下载/VMamba-main/kernels/selective_scan/csrc/selective_scan' -I/home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include -I/home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include/TH -I/home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include/THC -I/home/hhy/anaconda3/envs/mamba/include -I/home/hhy/anaconda3/envs/mamba/include/python3.10 -c -c '/home/hhy/下载/VMamba-main/kernels/selective_scan/csrc/selective_scan/cus/selective_scan_core_bwd.cu' -o '/home/hhy/下载/VMamba-main/kernels/selective_scan/build/temp.linux-x86_64-cpython-310/csrc/selective_scan/cus/selective_scan_core_bwd.o' -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -std=c++17 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_BFLOAT16_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -U__CUDA_NO_BFLOAT162_OPERATORS__ -U__CUDA_NO_BFLOAT162_CONVERSIONS__ --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --ptxas-options=-v -lineinfo -gencode arch=compute_70,code=sm_70 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_90,code=sm_90 --threads 4 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=selective_scan_cuda_core -D_GLIBCXX_USE_CXX11_ABI=0
      cc1plus: fatal error: cuda_runtime.h: 没有那个文件或目录
      compilation terminated.
      cc1plus: fatal error: cuda_runtime.h: 没有那个文件或目录
      compilation terminated.
      cc1plus: fatal error: cuda_runtime.h: 没有那个文件或目录
      compilation terminated.
      cc1plus: fatal error: cuda_runtime.h: 没有那个文件或目录
      compilation terminated.
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2100, in _run_ninja_build
          subprocess.run(
        File "/home/hhy/anaconda3/envs/mamba/lib/python3.10/subprocess.py", line 526, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/hhy/下载/VMamba-main/kernels/selective_scan/setup.py", line 140, in <module>
          setup(
        File "/home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages/setuptools/__init__.py", line 104, in setup
          return distutils.core.setup(**attrs)
        File "/home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
        File "/home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "/home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 91, in run
          _build_ext.run(self)
        File "/home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
        File "/home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 873, in build_extensions
          build_ext.build_extensions(self)
        File "/home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 479, in build_extensions
          self._build_extensions_serial()
        File "/home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 505, in _build_extensions_serial
          self.build_extension(ext)
        File "/home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 252, in build_extension
          _build_ext.build_extension(self, ext)
        File "/home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 560, in build_extension
          objects = self.compiler.compile(
        File "/home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 686, in unix_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "/home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1774, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "/home/hhy/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2116, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for selective_scan
  Running setup.py clean for selective_scan
Failed to build selective_scan
ERROR: Could not build wheels for selective_scan, which is required to install pyproject.toml-based projects

**Comment by ljyljy1216** [comment]
u can learn from question #161 

I hope I can help u.
