### ISSUE TITLE
RuntimeError: memory format option is only supported by strided tensors

### ISSUE THREAD

**Issue by ljyljy1216** [MzeroMiko/VMamba#175]
When I applied the model to my own task, the following error occurred. But I have strided tensors for each one, and I still get the following error. Does anyone know why that is

`Traceback (most recent call last):
  File "/mnt/c/Users/caica/Desktop/swin/classes/fc4/train.py", line 283, in <module>
    main(opt)
  File "/mnt/c/Users/caica/Desktop/swin/classes/fc4/train.py", line 105, in main
    loss = model.optimize(img, label)
  File "/mnt/c/Users/caica/Desktop/swin/classes/fc4/Model_FC4.py", line 40, in optimize
    pred = self.predict(img)
  File "/mnt/c/Users/caica/Desktop/swin/classes/fc4/Model_FC4.py", line 32, in predict
    pred, rgb, confidence = self._network(img)
  File "/home/liujunyi/anaconda3/envs/vmamba2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/liujunyi/anaconda3/envs/vmamba2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/c/Users/caica/Desktop/swin/classes/fc4/FC_4.py", line 69, in forward
    x = self.backbone(x)
  File "/home/liujunyi/anaconda3/envs/vmamba2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/liujunyi/anaconda3/envs/vmamba2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/c/Users/caica/Desktop/swin/classes/fc4/VMamba_main/classification/models/vmamba.py", line 1514, in forward
    o, x = layer_forward(layer, x) # (B, H, W, C)
  File "/mnt/c/Users/caica/Desktop/swin/classes/fc4/VMamba_main/classification/models/vmamba.py", line 1507, in layer_forward
    x = l.blocks(x)
  File "/home/liujunyi/anaconda3/envs/vmamba2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/liujunyi/anaconda3/envs/vmamba2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/liujunyi/anaconda3/envs/vmamba2/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/liujunyi/anaconda3/envs/vmamba2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/liujunyi/anaconda3/envs/vmamba2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/c/Users/caica/Desktop/swin/classes/fc4/VMamba_main/classification/models/vmamba.py", line 1161, in forward
    return self._forward(input)
  File "/mnt/c/Users/caica/Desktop/swin/classes/fc4/VMamba_main/classification/models/vmamba.py", line 1149, in _forward
    x = x + self.drop_path(self.op(self.norm(x)))
  File "/home/liujunyi/anaconda3/envs/vmamba2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/liujunyi/anaconda3/envs/vmamba2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/c/Users/caica/Desktop/swin/classes/fc4/VMamba_main/classification/models/vmamba.py", line 745, in forwardv2
    y = self.forward_core(x)
  File "/mnt/c/Users/caica/Desktop/swin/classes/fc4/VMamba_main/classification/models/vmamba.py", line 706, in forward_corev2
    ys: torch.Tensor = selective_scan(
  File "/mnt/c/Users/caica/Desktop/swin/classes/fc4/VMamba_main/classification/models/vmamba.py", line 598, in selective_scan
    return SelectiveScan.apply(u, delta, A, B, C, D, delta_bias, delta_softplus, nrows, backnrows, ssoflex)
  File "/home/liujunyi/anaconda3/envs/vmamba2/lib/python3.10/site-packages/torch/autograd/function.py", line 553, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/liujunyi/anaconda3/envs/vmamba2/lib/python3.10/site-packages/torch/cuda/amp/autocast_mode.py", line 115, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/mnt/c/Users/caica/Desktop/swin/classes/fc4/VMamba_main/classification/models/csms6s.py", line 267, in forward
    out, x, *rest = selective_scan_cuda_core.fwd(u, delta, A, B, C, D, delta_bias, delta_softplus, 1)
RuntimeError: memory format option is only supported by strided tensors`

**Comment by kititoo** [comment]
Hello!!!
I also encountered the same problem, can you solve it please?
QAQ  ^^

**Comment by MzeroMiko** [comment]
Do all data (u, delta, A, B, C, D, delta_bias) contiguous in your application?

**Comment by ljyljy1216** [comment]
> Hello!!! I also encountered the same problem, can you solve it please? QAQ ^^

I updated the version of pytorch and I solved this problem.becauseI I found that I did not install the selective_scan package properly

**Comment by GHZAI** [comment]
> > Hello!!! I also encountered the same problem, can you solve it please? QAQ ^^
> 
> I updated the version of pytorch and I solved this problem.becauseI I found that I did not install the selective_scan package properly

Hello, can you send me the details of how you did it?

**Comment by ytl49** [comment]
> > Hello!!! I also encountered the same problem, can you solve it please? QAQ ^^
> 
> I updated the version of pytorch and I solved this problem.becauseI I found that I did not install the selective_scan package properly

can you tell me your pytorch version?

**Comment by ljyljy1216** [comment]
> > > Hello!!! I also encountered the same problem, can you solve it please? QAQ ^^
> > 
> > 
> > I updated the version of pytorch and I solved this problem.becauseI I found that I did not install the selective_scan package properly
> 
> can you tell me your pytorch version?

2.1.1+cu121 cuda version=12.3
