### ISSUE TITLE
将主干移植到mmrotate时出现问题

### ISSUE THREAD

**Issue by 310war** [MzeroMiko/VMamba#188]
我在将主干网注册到mmrotate后，重新训练时出现问题：
2024-05-10 17:10:28,758 - mmrotate - INFO - Set random seed to 0, deterministic: False
Traceback (most recent call last):
  File "/home/user2023/.conda/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "/home/user2023/wangaoran/PKINet-main/mmrotate/models/backbones/vmamba/detection/model.py", line 35, in __init__
    BaseModule.__init__(self)
  File "/home/user2023/.conda/envs/openmmlab/lib/python3.8/site-packages/mmengine/model/base_module.py", line 45, in __init__
    super().__init__()
  File "/home/user2023/wangaoran/PKINet-main/mmrotate/models/backbones/vmamba/classification/models/vmamba.py", line 1478, in __init__
    super().__init__(**kwargs)
  File "/home/user2023/wangaoran/PKINet-main/mmrotate/models/backbones/vmamba/classification/models/vmamba.py", line 1229, in __init__
    self.layers.append(self._make_layer(
  File "/home/user2023/wangaoran/PKINet-main/mmrotate/models/backbones/vmamba/classification/models/vmamba.py", line 1364, in _make_layer
    blocks.append(VSSBlock(
  File "/home/user2023/wangaoran/PKINet-main/mmrotate/models/backbones/vmamba/classification/models/vmamba.py", line 1078, in __init__
    self.op = SS2D(
  File "/home/user2023/wangaoran/PKINet-main/mmrotate/models/backbones/vmamba/classification/models/vmamba.py", line 1032, in __init__
    self.__initv2__(**kwargs)
  File "/home/user2023/wangaoran/PKINet-main/mmrotate/models/backbones/vmamba/classification/models/vmamba.py", line 498, in __initv2__
    self.conv2d = nn.Conv2d(
TypeError: __init__() got an unexpected keyword argument 'device'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user2023/.conda/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "/home/user2023/wangaoran/PKINet-main/mmrotate/models/detectors/oriented_rcnn.py", line 24, in __init__
    super(OrientedRCNN, self).__init__(
  File "/home/user2023/wangaoran/PKINet-main/mmrotate/models/detectors/two_stage.py", line 32, in __init__
    self.backbone = build_backbone(backbone)
  File "/home/user2023/wangaoran/PKINet-main/mmrotate/models/builder.py", line 17, in build_backbone
    return ROTATED_BACKBONES.build(cfg)
  File "/home/user2023/.conda/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/user2023/.conda/envs/openmmlab/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/user2023/.conda/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: MM_VSSM: __init__() got an unexpected keyword argument 'device'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./tools/train.py", line 194, in <module>
    main()
  File "./tools/train.py", line 163, in main
    model = build_detector(
  File "/home/user2023/wangaoran/PKINet-main/mmrotate/models/builder.py", line 55, in build_detector
    return ROTATED_DETECTORS.build(
  File "/home/user2023/.conda/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/user2023/.conda/envs/openmmlab/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/user2023/.conda/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: OrientedRCNN: MM_VSSM: __init__() got an unexpected keyword argument 'device'

**Comment by icecreamovo147** [comment]
> 我在将主干网注册到mmrotate后，重新训练时出现问题： 2024-05-10 17:10:28,758 - mmrotate - INFO - Set random seed to 0, deterministic: False Traceback (most recent call last): File "/home/user2023/.conda/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg return obj_cls(**args) File "/home/user2023/wangaoran/PKINet-main/mmrotate/models/backbones/vmamba/detection/model.py", line 35, in **init** BaseModule.**init**(self) File "/home/user2023/.conda/envs/openmmlab/lib/python3.8/site-packages/mmengine/model/base_module.py", line 45, in **init** super().**init**() File "/home/user2023/wangaoran/PKINet-main/mmrotate/models/backbones/vmamba/classification/models/vmamba.py", line 1478, in **init** super().**init**(**kwargs) File "/home/user2023/wangaoran/PKINet-main/mmrotate/models/backbones/vmamba/classification/models/vmamba.py", line 1229, in **init** self.layers.append(self._make_layer( File "/home/user2023/wangaoran/PKINet-main/mmrotate/models/backbones/vmamba/classification/models/vmamba.py", line 1364, in _make_layer blocks.append(VSSBlock( File "/home/user2023/wangaoran/PKINet-main/mmrotate/models/backbones/vmamba/classification/models/vmamba.py", line 1078, in **init** self.op = SS2D( File "/home/user2023/wangaoran/PKINet-main/mmrotate/models/backbones/vmamba/classification/models/vmamba.py", line 1032, in **init** self.**initv2**(**kwargs) File "/home/user2023/wangaoran/PKINet-main/mmrotate/models/backbones/vmamba/classification/models/vmamba.py", line 498, in **initv2** self.conv2d = nn.Conv2d( TypeError: **init**() got an unexpected keyword argument 'device'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/home/user2023/.conda/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg return obj_cls(**args) File "/home/user2023/wangaoran/PKINet-main/mmrotate/models/detectors/oriented_rcnn.py", line 24, in **init** super(OrientedRCNN, self).**init**( File "/home/user2023/wangaoran/PKINet-main/mmrotate/models/detectors/two_stage.py", line 32, in **init** self.backbone = build_backbone(backbone) File "/home/user2023/wangaoran/PKINet-main/mmrotate/models/builder.py", line 17, in build_backbone return ROTATED_BACKBONES.build(cfg) File "/home/user2023/.conda/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 237, in build return self.build_func(*args, **kwargs, registry=self) File "/home/user2023/.conda/envs/openmmlab/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg return build_from_cfg(cfg, registry, default_args) File "/home/user2023/.conda/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg raise type(e)(f'{obj_cls.**name**}: {e}') TypeError: MM_VSSM: **init**() got an unexpected keyword argument 'device'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "./tools/train.py", line 194, in main() File "./tools/train.py", line 163, in main model = build_detector( File "/home/user2023/wangaoran/PKINet-main/mmrotate/models/builder.py", line 55, in build_detector return ROTATED_DETECTORS.build( File "/home/user2023/.conda/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 237, in build return self.build_func(*args, **kwargs, registry=self) File "/home/user2023/.conda/envs/openmmlab/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg return build_from_cfg(cfg, registry, default_args) File "/home/user2023/.conda/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg raise type(e)(f'{obj_cls.**name**}: {e}') TypeError: OrientedRCNN: MM_VSSM: **init**() got an unexpected keyword argument 'device'

Hi, I have the same problem, have you solved it? What version of mmcv-full and pytorch do you use?
