### ISSUE TITLE
when running pip install . encounter error

### ISSUE THREAD

**Issue by icey-cola** [MzeroMiko/VMamba#191]
error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [92 lines of output]

      torch.__version__  = 2.2.2+cu121

      CUDA_HOME = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.0

      CUDA version:  12.0
      running bdist_wheel
      running build
      running build_ext
      C:\Users\57458\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\cpp_extension.py:381: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
        warnings.warn(f'Error checking compiler version for {compiler}: {error}')
      C:\Users\57458\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\cpp_extension.py:415: UserWarning: The detected CUDA version (12.0) has a minor version mismatch with the version that was used to compile PyTorch (12.1). Most likely this shouldn't be a problem.
        warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
      building 'selective_scan_cuda_core' extension
      creating C:\Users\57458\Desktop\新建文件夹\VMamba\kernels\selective_scan\build
      creating C:\Users\57458\Desktop\新建文件夹\VMamba\kernels\selective_scan\build\temp.win-amd64-cpython-310
      creating C:\Users\57458\Desktop\新建文件夹\VMamba\kernels\selective_scan\build\temp.win-amd64-cpython-310\Release
      creating C:\Users\57458\Desktop\新建文件夹\VMamba\kernels\selective_scan\build\temp.win-amd64-cpython-310\Release\csrc
      creating C:\Users\57458\Desktop\新建文件夹\VMamba\kernels\selective_scan\build\temp.win-amd64-cpython-310\Release\csrc\selective_scan
      creating C:\Users\57458\Desktop\新建文件夹\VMamba\kernels\selective_scan\build\temp.win-amd64-cpython-310\Release\csrc\selective_scan\cus
      Emitting ninja build file C:\Users\57458\Desktop\新建文件夹\VMamba\kernels\selective_scan\build\temp.win-amd64-cpython-310\Release\build.ninja...
      Compiling objects...
      Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
      ninja: error: 'C:/Users/57458/Desktop/新建文件夹/VMamba/kernels/selective_scan/csrc/selective_scan/cus/selective_scan.cpp', needed by 'C:/Users/57458/Desktop/新建文件夹/VMamba/kernels/selective_scan/build/temp.win-amd64-cpython-310/Release/csrc/selective_scan/cus/selective_scan.obj', missing and no known rule to make it
      Traceback (most recent call last):
        File "C:\Users\57458\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\cpp_extension.py", line 2096, in _run_ninja_build
          subprocess.run(
        File "C:\Users\57458\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 526, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\57458\Desktop\新建文件夹\VMamba\kernels\selective_scan\setup.py", line 142, in <module>
          setup(
        File "C:\Users\57458\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\57458\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\57458\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\57458\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "C:\Users\57458\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Users\57458\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Users\57458\AppData\Local\Programs\Python\Python310\lib\site-packages\wheel\bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "C:\Users\57458\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "C:\Users\57458\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Users\57458\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Users\57458\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
          self.run_command(cmd_name)
        File "C:\Users\57458\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "C:\Users\57458\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Users\57458\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Users\57458\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
          _build_ext.run(self)
        File "C:\Users\57458\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
          self.build_extensions()
        File "C:\Users\57458\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\cpp_extension.py", line 871, in build_extensions
          build_ext.build_extensions(self)
        File "C:\Users\57458\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 466, in build_extensions
          self._build_extensions_serial()
        File "C:\Users\57458\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 492, in _build_extensions_serial
          self.build_extension(ext)
        File "C:\Users\57458\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\build_ext.py", line 246, in build_extension
          _build_ext.build_extension(self, ext)
        File "C:\Users\57458\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 547, in build_extension
          objects = self.compiler.compile(
        File "C:\Users\57458\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\cpp_extension.py", line 843, in win_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "C:\Users\57458\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\cpp_extension.py", line 1774, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "C:\Users\57458\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\cpp_extension.py", line 2112, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for selective-scan
  Running setup.py clean for selective-scan
Failed to build selective-scan
ERROR: Could not build wheels for selective-scan, which is required to install pyproject.toml-based projects

so what happened and how i fix it 
thanks a lot

**Comment by 66YanWang** [comment]
me too

**Comment by MzeroMiko** [comment]
you can try python setup.py install for more detailed error infomations.
