### ISSUE TITLE
Error when installing selective_scan

### ISSUE THREAD

**Issue by bryanbocao** [MzeroMiko/VMamba#251]
```
(vmamba) brcao@dawn:/eData05/brcao/Repos/VMamba/kernels/selective_scan$ pip install .
Defaulting to user installation because normal site-packages is not writeable
Processing /eData05/brcao/Repos/VMamba/kernels/selective_scan
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/eData05/brcao/Repos/VMamba/kernels/selective_scan/setup.py", line 18, in <module>
          from torch.utils.cpp_extension import (
        File "/home/brcao/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 28, in <module>          from pkg_resources import packaging  # type: ignore[attr-defined]
      ImportError: cannot import name 'packaging' from 'pkg_resources' (/home/brcao/.local/lib/python3.8/site-packages/pkg_resources/__init__.py)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
(vmamba) brcao@dawn:/eData05/brcao/Repos/VMamba/kernels/selective_scan$ pip install --upgrade pip
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pip in /home/brcao/.local/lib/python3.8/site-packages (24.1.1)
WARNING: Error parsing dependencies of distro-info: Invalid version: '0.23ubuntu1'
WARNING: Error parsing dependencies of python-debian: Invalid version: '0.1.36ubuntu1'
```
GPU: 3090-Ti

**Comment by MzeroMiko** [comment]
It seems that you have not installed the package `packaging`. Install it and try again.

**Comment by bryanbocao** [comment]
@MzeroMiko Thanks for the reply.

I tried this and got
```
(vmamba) brcao@dawn:/eData05/brcao/Repos/VMamba/kernels/selective_scan$ pip install packaging
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: packaging in /home/brcao/.local/lib/python3.8/site-packages (24.1)
WARNING: Error parsing dependencies of distro-info: Invalid version: '0.23ubuntu1'
WARNING: Error parsing dependencies of python-debian: Invalid version: '0.1.36ubuntu1'
```

**Comment by bryanbocao** [comment]
It's related to CUDA, PyTorch and Python versions. Long story short, I finally was able to resolve that in a docker container by ```pytorch/pytorch:2.3.1-cuda12.1-cudnn8-devel``` image:
```
sudo docker pull pytorch/pytorch:2.3.1-cuda12.1-cudnn8-devel
(vmamba) brcao@dawn:/eData05/brcao/Repos/UDA_SCI$ sudo docker pull pytorch/pytorch:2.3.1-cuda12.1-cudnn8-devel
2.3.1-cuda12.1-cudnn8-devel: Pulling from pytorch/pytorch
43f89b94cd7d: Pull complete
dd4939a04761: Pull complete
b0d7cc89b769: Pull complete
1532d9024b9c: Pull complete
04fc8a31fa53: Pull complete
a14a8a8a6ebc: Pull complete
7d61afc7a3ac: Pull complete
8bd2762ffdd9: Pull complete
2a5ee6fadd42: Pull complete
22ba0fb08ae2: Pull complete
4d37a6bba88f: Pull complete
4bc954eb910a: Pull complete
165aad6fabd0: Pull complete
c49c630af66e: Pull complete
4f4fb700ef54: Pull complete
ad3e53217d5f: Pull complete
Digest: sha256:a22a1fca37f8361c8a1e859cd6eb6bd9d1fb384f9c0dcb2cfc691a178eb03d17
Status: Downloaded newer image for pytorch/pytorch:2.3.1-cuda12.1-cudnn8-devel
docker.io/pytorch/pytorch:2.3.1-cuda12.1-cudnn8-devel

(vmamba) brcao@dawn:/eData05/brcao/Repos/UDA_SCI$ sudo docker run -d --ipc=host --shm-size=16384m -it -v /:/share --gpus all --network=bridge pytorch/pytorch:2.3.1-cuda12.1-cudnn8-devel /bin/bash
829a32bfc3806faed90ab16c591dfb9eb96390bd6574e64fef842159f8033e7a
(vmamba) brcao@dawn:/eData05/brcao/Repos/UDA_SCI$ sudo docker ps -a
CONTAINER ID   IMAGE                                         COMMAND                  CREATED          STATUS          PORTS                NAMES
829a32bfc380   pytorch/pytorch:2.3.1-cuda12.1-cudnn8-devel   "/opt/nvidia/nvidia_…"   6 seconds ago    Up 4 seconds                         goofy_cori
814ed2da2305   anibali/pytorch:2.0.1-cuda11.8                "/bin/bash"              25 minutes ago   Up 25 minutes                        great_jackson
dd28bbe17556   chainguard/pytorch-cuda12                     "/usr/share/torchvis…"   35 minutes ago   Created                              condescending_fermat
80075526ea00   chainguard/pytorch-cuda12:latest              "/usr/share/torchvis…"   36 minutes ago   Created                              competent_goldberg
00f687f444b0   pytorch/manylinux-cuda121                     "/bin/bash"              2 hours ago      Up 2 hours                           blissful_elion
f7ffd30bb6ae   bryanbocao/tsa_net_pytorch                    "/bin/bash"              2 days ago       Up 2 days                            boring_ptolemy
87e0eeff525e   bryanbocao/tsa_net_pytorch                    "/bin/bash"              2 days ago       Up 2 days                            musing_spence
1acd0c9d4581   bryanbocao/tsa_net_pytorch                    "/bin/bash"              2 days ago       Up 2 days                            eloquent_raman
6c181005d7ea   nvcr.io/nvidia/pytorch:pytorchCompare         "/opt/nvidia/nvidia_…"   2 weeks ago      Up 2 weeks      6006/tcp, 8888/tcp   nervous_lamarr
8336aec918d2   nvcr.io/nvidia/pytorch:24.01-py3              "/opt/nvidia/nvidia_…"   2 weeks ago      Up 2 weeks      6006/tcp, 8888/tcp   quirky_hoover

(vmamba) brcao@dawn:/eData05/brcao/Repos/UDA_SCI$ sudo docker exec -it 829a32bfc380 /bin/bash
root@829a32bfc380:/workspace# nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Mon_Apr__3_17:16:06_PDT_2023
Cuda compilation tools, release 12.1, V12.1.105
Build cuda_12.1.r12.1/compiler.32688072_0
root@829a32bfc380:/workspace#

root@829a32bfc380:/workspace# cd /share/eData05/brcao/Repos/VMamba/
root@829a32bfc380:/share/eData05/brcao/Repos/VMamba# pip install -r requirements.txt

Downloading tzdata-2024.1-py2.py3-none-any.whl (345 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 345.4/345.4 kB 17.7 MB/s eta 0:00:00
Downloading portalocker-2.10.0-py3-none-any.whl (18 kB)
Building wheels for collected packages: fvcore, iopath
  Building wheel for fvcore (setup.py) ... done
  Created wheel for fvcore: filename=fvcore-0.1.5.post20221221-py3-none-any.whl size=61400 sha256=a7e1b0731ef02b4b05beb1061d56fe4202ae0254e161038d3bf9c0bd5c7e1ed1
  Stored in directory: /root/.cache/pip/wheels/01/c0/af/77c1cf53a1be9e42a52b48e5af2169d40ec2e89f7362489dd0
  Building wheel for iopath (setup.py) ... done
  Created wheel for iopath: filename=iopath-0.1.10-py3-none-any.whl size=31532 sha256=5abf8aa7d3d30fee13835e1c73359e2cc703a87e3408a040f9e8e92929ecc6dd
  Stored in directory: /root/.cache/pip/wheels/9a/a3/b6/ac0fcd1b4ed5cfeb3db92e6a0e476cfd48ed0df92b91080c1d
Successfully built fvcore iopath
Installing collected packages: yacs, tzdata, termcolor, tabulate, python-dateutil, pyparsing, protobuf, portalocker, pluggy, kiwisolver, iniconfig, fonttools, cycler, contourpy, cloudpickle, tensorboardX, submitit, pytest, pandas, matplotlib, iopath, seaborn, fvcore, timm
  Attempting uninstall: pluggy
    Found existing installation: pluggy 1.0.0
    Uninstalling pluggy-1.0.0:
      Successfully uninstalled pluggy-1.0.0
Successfully installed cloudpickle-3.0.0 contourpy-1.2.1 cycler-0.12.1 fonttools-4.53.0 fvcore-0.1.5.post20221221 iniconfig-2.0.0 iopath-0.1.10 kiwisolver-1.4.5 matplotlib-3.9.0 pandas-2.2.2 pluggy-1.5.0 portalocker-2.10.0 protobuf-5.27.2 pyparsing-3.1.2 pytest-8.2.2 python-dateutil-2.9.0.post0 seaborn-0.13.2 submitit-1.5.1 tabulate-0.9.0 tensorboardX-2.6.2.2 termcolor-2.4.0 timm-0.4.12 tzdata-2024.1 yacs-0.1.8
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

root@829a32bfc380:/share/eData05/brcao/Repos/VMamba# cd kernels/selective_scan && pip install .
Processing /share/eData05/brcao/Repos/VMamba/kernels/selective_scan
  Preparing metadata (setup.py) ... done
Requirement already satisfied: torch in /opt/conda/lib/python3.10/site-packages (from selective_scan==0.0.2) (2.3.1)
Requirement already satisfied: packaging in /opt/conda/lib/python3.10/site-packages (from selective_scan==0.0.2) (23.2)
Collecting ninja (from selective_scan==0.0.2)
  Downloading ninja-1.11.1.1-py2.py3-none-manylinux1_x86_64.manylinux_2_5_x86_64.whl.metadata (5.3 kB)
Collecting einops (from selective_scan==0.0.2)
  Downloading einops-0.8.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: filelock in /opt/conda/lib/python3.10/site-packages (from torch->selective_scan==0.0.2) (3.13.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /opt/conda/lib/python3.10/site-packages (from torch->selective_scan==0.0.2) (4.11.0)
Requirement already satisfied: sympy in /opt/conda/lib/python3.10/site-packages (from torch->selective_scan==0.0.2) (1.12.1)
Requirement already satisfied: networkx in /opt/conda/lib/python3.10/site-packages (from torch->selective_scan==0.0.2) (3.2.1)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.10/site-packages (from torch->selective_scan==0.0.2) (3.1.4)
Requirement already satisfied: fsspec in /opt/conda/lib/python3.10/site-packages (from torch->selective_scan==0.0.2) (2024.6.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.10/site-packages (from jinja2->torch->selective_scan==0.0.2) (2.1.3)
Requirement already satisfied: mpmath<1.4.0,>=1.1.0 in /opt/conda/lib/python3.10/site-packages (from sympy->torch->selective_scan==0.0.2) (1.3.0)
Downloading einops-0.8.0-py3-none-any.whl (43 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.2/43.2 kB 1.7 MB/s eta 0:00:00
Downloading ninja-1.11.1.1-py2.py3-none-manylinux1_x86_64.manylinux_2_5_x86_64.whl (307 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 307.2/307.2 kB 8.4 MB/s eta 0:00:00
Building wheels for collected packages: selective_scan
^@  Building wheel for selective_scan (setup.py) ... -
root@829a32bfc380:/share/eData05/brcao/Repos/VMamba# cd kernels/selective_scan && pip install .
Processing /share/eData05/brcao/Repos/VMamba/kernels/selective_scan
  Preparing metadata (setup.py) ... done
Requirement already satisfied: torch in /opt/conda/lib/python3.10/site-packages (from selective_scan==0.0.2) (2.3.1)
Requirement already satisfied: packaging in /opt/conda/lib/python3.10/site-packages (from selective_scan==0.0.2) (23.2)
Collecting ninja (from selective_scan==0.0.2)
  Downloading ninja-1.11.1.1-py2.py3-none-manylinux1_x86_64.manylinux_2_5_x86_64.whl.metadata (5.3 kB)
Collecting einops (from selective_scan==0.0.2)
  Downloading einops-0.8.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: filelock in /opt/conda/lib/python3.10/site-packages (from torch->selective_scan==0.0.2) (3.13.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /opt/conda/lib/python3.10/site-packages (from torch->selective_scan==0.0.2) (4.11.0)
Requirement already satisfied: sympy in /opt/conda/lib/python3.10/site-packages (from torch->selective_scan==0.0.2) (1.12.1)
Requirement already satisfied: networkx in /opt/conda/lib/python3.10/site-packages (from torch->selective_scan==0.0.2) (3.2.1)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.10/site-packages (from torch->selective_scan==0.0.2) (3.1.4)
Requirement already satisfied: fsspec in /opt/conda/lib/python3.10/site-packages (from torch->selective_scan==0.0.2) (2024.6.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.10/site-packages (from jinja2->torch->selective_scan==0.0.2) (2.1.3)
Requirement already satisfied: mpmath<1.4.0,>=1.1.0 in /opt/conda/lib/python3.10/site-packages (from sympy->torch->selective_scan==0.0.2) (1.3.0)
Downloading einops-0.8.0-py3-none-any.whl (43 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.2/43.2 kB 1.7 MB/s eta 0:00:00
Downloading ninja-1.11.1.1-py2.py3-none-manylinux1_x86_64.manylinux_2_5_x86_64.whl (307 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 307.2/307.2 kB 8.4 MB/s eta 0:00:00
Building wheels for collected packages: selective_scan
^@  Building wheel for selective_scan (setup.py) ... -


^done
  Created wheel for selective_scan: filename=selective_scan-0.0.2-cp310-cp310-linux_x86_64.whl size=11632618 sha256=be88055a89072fb382e7683a9b07b116a3476742cc6e6bfaa7560010b79f6739
  Stored in directory: /tmp/pip-ephem-wheel-cache-wvq_zmjn/wheels/96/47/2a/d6a5add371d500594ee7526422a3c61e7eabcaeaad4fe691a2
Successfully built selective_scan
Installing collected packages: ninja, einops, selective_scan
Successfully installed einops-0.8.0 ninja-1.11.1.1 selective_scan-0.0.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
```
