### ISSUE TITLE
Error when doing classification fine-tuning with checkpoint

### ISSUE THREAD

**Issue by ChiShengChen** [MzeroMiko/VMamba#27]
I meet the error below when I use the latest version code with classification checkpoint:
`AttributeError: 'VSSM' object has no attribute 'head'` with the checkpoint `vmamba_small_e238_ema.pth`

Complete log:
```
[2024-02-05 08:58:46 vssm_small](main.py 171): INFO no checkpoint found in /tmp/vssm_small/default, ignoring auto resume
[2024-02-05 08:58:46 vssm_small](utils_ema.py 132): INFO ==============> Loading weight /home/csc/VMamba/classification/pretrained/vmamba_small_e238_ema.pth for fine-tuning......
Traceback (most recent call last):
  File "/home/csc/VMamba/classification/main.py", line 409, in <module>
    main(config)
  File "/home/csc/VMamba/classification/main.py", line 185, in main
    load_pretrained_ema(config, model_without_ddp, logger, model_ema)
  File "/home/csc/VMamba/classification/utils/utils_ema.py", line 135, in load_pretrained_ema
    _load_pretrained(config, model, logger, state_dict)
  File "/home/csc/VMamba/classification/utils/utils_ema.py", line 105, in _load_pretrained
    Nc2 = model.head.bias.shape[0]
  File "/home/csc/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1265, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'VSSM' object has no attribute 'head'

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 5997) of binary: /home/csc/anaconda3/envs/vmamba/bin/python
Traceback (most recent call last):
  File "/home/csc/anaconda3/envs/vmamba/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/csc/anaconda3/envs/vmamba/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/csc/.local/lib/python3.10/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/home/csc/.local/lib/python3.10/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/home/csc/.local/lib/python3.10/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/home/csc/.local/lib/python3.10/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/csc/.local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/csc/.local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
main.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-02-05_08:58:48
  host      : csc-System-Product-Name
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 5997)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

```

The commad:
`python -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=1 --master_addr="127.0.0.1" --master_port=29501 main.py --cfg configs/vssm/vssm_small_224.yaml --batch-size 32 --data-path /home/csc/my_data --pretrained /home/csc/VMamba/classification/pretrained/vmamba_small_e238_ema.pth  --output /tmp`

**Comment by MzeroMiko** [comment]
Thank you for reporting that bug. As we did not release imagenet22k pretraining, just ignore this bug is ok. In the new file, we have ignore all the [`22k to 1k transferring codes`](https://github.com/MzeroMiko/VMamba/blob/main/classification/utils/utils_ema.py#L46).

**Comment by sivaji123256** [comment]
@ChiShengChen and @MzeroMiko , I have tried the following as well.But,stil the same issue persisting.
checkpoint_state_dict = checkpoint['model']
        current_model_state_dict = model.state_dict()
        # Create a new state dictionary by comparing the sizes of tensors
        new_state_dict = {}
        for k, v in current_model_state_dict.items():
            if k in checkpoint_state_dict and v.size() == checkpoint_state_dict[k].size():
                new_state_dict[k] = checkpoint_state_dict[k]
            else:
                new_state_dict[k] = v
        # Load the new state dictionary into the model
        msg = model.load_state_dict(new_state_dict, strict=False)
