### ISSUE TITLE
when cd kernels/selective_scan && pip install .  encountered this error

### ISSUE THREAD

**Issue by Alittlemole** [MzeroMiko/VMamba#324]
Building wheel for selective-scan (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [186 lines of output]
      
      
      torch.__version__  = 2.1.1+cu118
      
      
      
      
      CUDA_HOME = /home/xys/anaconda3/envs/mamba
      
      
      CUDA version:  11.8
      running bdist_wheel
      running build
      running build_ext
      /home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/utils/cpp_extension.py:424: UserWarning: There are no g++ version bounds defined for CUDA version 11.8
        warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
      building 'selective_scan_cuda_oflex' extension
      creating /home/xys/paper_code/VMamba-main/kernels/selective_scan/build
      creating /home/xys/paper_code/VMamba-main/kernels/selective_scan/build/temp.linux-x86_64-cpython-310
      creating /home/xys/paper_code/VMamba-main/kernels/selective_scan/build/temp.linux-x86_64-cpython-310/csrc
      creating /home/xys/paper_code/VMamba-main/kernels/selective_scan/build/temp.linux-x86_64-cpython-310/csrc/selective_scan
      creating /home/xys/paper_code/VMamba-main/kernels/selective_scan/build/temp.linux-x86_64-cpython-310/csrc/selective_scan/cusoflex
      Emitting ninja build file /home/xys/paper_code/VMamba-main/kernels/selective_scan/build/temp.linux-x86_64-cpython-310/build.ninja...
      Compiling objects...
      Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
      [1/3] /home/xys/anaconda3/envs/mamba/bin/nvcc  -I/home/xys/paper_code/VMamba-main/kernels/selective_scan/csrc/selective_scan -I/home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include -I/home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include/TH -I/home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include/THC -I/home/xys/anaconda3/envs/mamba/include -I/home/xys/anaconda3/envs/mamba/include/python3.10 -c -c /home/xys/paper_code/VMamba-main/kernels/selective_scan/csrc/selective_scan/cusoflex/selective_scan_core_fwd.cu -o /home/xys/paper_code/VMamba-main/kernels/selective_scan/build/temp.linux-x86_64-cpython-310/csrc/selective_scan/cusoflex/selective_scan_core_fwd.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -std=c++17 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_BFLOAT16_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -U__CUDA_NO_BFLOAT162_OPERATORS__ -U__CUDA_NO_BFLOAT162_CONVERSIONS__ --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --ptxas-options=-v -lineinfo -gencode arch=compute_60,code=sm_60 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_90,code=sm_90 --threads 4 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=selective_scan_cuda_oflex -D_GLIBCXX_USE_CXX11_ABI=0
      FAILED: /home/xys/paper_code/VMamba-main/kernels/selective_scan/build/temp.linux-x86_64-cpython-310/csrc/selective_scan/cusoflex/selective_scan_core_fwd.o
      /home/xys/anaconda3/envs/mamba/bin/nvcc  -I/home/xys/paper_code/VMamba-main/kernels/selective_scan/csrc/selective_scan -I/home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include -I/home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include/TH -I/home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include/THC -I/home/xys/anaconda3/envs/mamba/include -I/home/xys/anaconda3/envs/mamba/include/python3.10 -c -c /home/xys/paper_code/VMamba-main/kernels/selective_scan/csrc/selective_scan/cusoflex/selective_scan_core_fwd.cu -o /home/xys/paper_code/VMamba-main/kernels/selective_scan/build/temp.linux-x86_64-cpython-310/csrc/selective_scan/cusoflex/selective_scan_core_fwd.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -std=c++17 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_BFLOAT16_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -U__CUDA_NO_BFLOAT162_OPERATORS__ -U__CUDA_NO_BFLOAT162_CONVERSIONS__ --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --ptxas-options=-v -lineinfo -gencode arch=compute_60,code=sm_60 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_90,code=sm_90 --threads 4 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=selective_scan_cuda_oflex -D_GLIBCXX_USE_CXX11_ABI=0
      In file included from /usr/include/cuda_runtime.h:83,
                       from <command-line>:
      /usr/include/crt/host_config.h:138:2: error: #error -- unsupported GNU version! gcc versions later than 8 are not supported!
        138 | #error -- unsupported GNU version! gcc versions later than 8 are not supported!
            |  ^~~~~
      In file included from /home/xys/paper_code/VMamba-main/kernels/selective_scan/csrc/selective_scan/cusoflex/selective_scan_fwd_kernel_oflex.cuh:7,
                       from /home/xys/paper_code/VMamba-main/kernels/selective_scan/csrc/selective_scan/cusoflex/selective_scan_core_fwd.cu:4:
      /home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include/c10/util/BFloat16.h:11:10: fatal error: cuda_bf16.h: 没有那个文件或目录
         11 | #include <cuda_bf16.h>
            |          ^~~~~~~~~~~~~
      compilation terminated.
      In file included from /usr/include/cuda_runtime.h:83,
                       from <command-line>:
      /usr/include/crt/host_config.h:138:2: error: #error -- unsupported GNU version! gcc versions later than 8 are not supported!
        138 | #error -- unsupported GNU version! gcc versions later than 8 are not supported!
            |  ^~~~~
      In file included from /home/xys/paper_code/VMamba-main/kernels/selective_scan/csrc/selective_scan/cusoflex/selective_scan_fwd_kernel_oflex.cuh:7,
                       from /home/xys/paper_code/VMamba-main/kernels/selective_scan/csrc/selective_scan/cusoflex/selective_scan_core_fwd.cu:4:
      /home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include/c10/util/BFloat16.h:11:10: fatal error: cuda_bf16.h: 没有那个文件或目录
         11 | #include <cuda_bf16.h>
            |          ^~~~~~~~~~~~~
      compilation terminated.
      In file included from /usr/include/cuda_runtime.h:83,
                       from <command-line>:
      /usr/include/crt/host_config.h:138:2: error: #error -- unsupported GNU version! gcc versions later than 8 are not supported!
        138 | #error -- unsupported GNU version! gcc versions later than 8 are not supported!
            |  ^~~~~
      In file included from /home/xys/paper_code/VMamba-main/kernels/selective_scan/csrc/selective_scan/cusoflex/selective_scan_fwd_kernel_oflex.cuh:7,
                       from /home/xys/paper_code/VMamba-main/kernels/selective_scan/csrc/selective_scan/cusoflex/selective_scan_core_fwd.cu:4:
      /home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include/c10/util/BFloat16.h:11:10: fatal error: cuda_bf16.h: 没有那个文件或目录
         11 | #include <cuda_bf16.h>
            |          ^~~~~~~~~~~~~
      compilation terminated.
      In file included from /usr/include/cuda_runtime.h:83,
                       from <command-line>:
      /usr/include/crt/host_config.h:138:2: error: #error -- unsupported GNU version! gcc versions later than 8 are not supported!
        138 | #error -- unsupported GNU version! gcc versions later than 8 are not supported!
            |  ^~~~~
      In file included from /home/xys/paper_code/VMamba-main/kernels/selective_scan/csrc/selective_scan/cusoflex/selective_scan_fwd_kernel_oflex.cuh:7,
                       from /home/xys/paper_code/VMamba-main/kernels/selective_scan/csrc/selective_scan/cusoflex/selective_scan_core_fwd.cu:4:
      /home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include/c10/util/BFloat16.h:11:10: fatal error: cuda_bf16.h: 没有那个文件或目录
         11 | #include <cuda_bf16.h>
            |          ^~~~~~~~~~~~~
      compilation terminated.
      [2/3] /home/xys/anaconda3/envs/mamba/bin/nvcc  -I/home/xys/paper_code/VMamba-main/kernels/selective_scan/csrc/selective_scan -I/home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include -I/home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include/TH -I/home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include/THC -I/home/xys/anaconda3/envs/mamba/include -I/home/xys/anaconda3/envs/mamba/include/python3.10 -c -c /home/xys/paper_code/VMamba-main/kernels/selective_scan/csrc/selective_scan/cusoflex/selective_scan_core_bwd.cu -o /home/xys/paper_code/VMamba-main/kernels/selective_scan/build/temp.linux-x86_64-cpython-310/csrc/selective_scan/cusoflex/selective_scan_core_bwd.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -std=c++17 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_BFLOAT16_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -U__CUDA_NO_BFLOAT162_OPERATORS__ -U__CUDA_NO_BFLOAT162_CONVERSIONS__ --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --ptxas-options=-v -lineinfo -gencode arch=compute_60,code=sm_60 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_90,code=sm_90 --threads 4 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=selective_scan_cuda_oflex -D_GLIBCXX_USE_CXX11_ABI=0
      FAILED: /home/xys/paper_code/VMamba-main/kernels/selective_scan/build/temp.linux-x86_64-cpython-310/csrc/selective_scan/cusoflex/selective_scan_core_bwd.o
      /home/xys/anaconda3/envs/mamba/bin/nvcc  -I/home/xys/paper_code/VMamba-main/kernels/selective_scan/csrc/selective_scan -I/home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include -I/home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include/TH -I/home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include/THC -I/home/xys/anaconda3/envs/mamba/include -I/home/xys/anaconda3/envs/mamba/include/python3.10 -c -c /home/xys/paper_code/VMamba-main/kernels/selective_scan/csrc/selective_scan/cusoflex/selective_scan_core_bwd.cu -o /home/xys/paper_code/VMamba-main/kernels/selective_scan/build/temp.linux-x86_64-cpython-310/csrc/selective_scan/cusoflex/selective_scan_core_bwd.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -std=c++17 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_BFLOAT16_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -U__CUDA_NO_BFLOAT162_OPERATORS__ -U__CUDA_NO_BFLOAT162_CONVERSIONS__ --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --ptxas-options=-v -lineinfo -gencode arch=compute_60,code=sm_60 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_90,code=sm_90 --threads 4 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=selective_scan_cuda_oflex -D_GLIBCXX_USE_CXX11_ABI=0
      In file included from /usr/include/cuda_runtime.h:83,
                       from <command-line>:
      /usr/include/crt/host_config.h:138:2: error: #error -- unsupported GNU version! gcc versions later than 8 are not supported!
        138 | #error -- unsupported GNU version! gcc versions later than 8 are not supported!
            |  ^~~~~
      In file included from /home/xys/paper_code/VMamba-main/kernels/selective_scan/csrc/selective_scan/cusoflex/selective_scan_bwd_kernel_oflex.cuh:7,
                       from /home/xys/paper_code/VMamba-main/kernels/selective_scan/csrc/selective_scan/cusoflex/selective_scan_core_bwd.cu:4:
      /home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include/c10/util/BFloat16.h:11:10: fatal error: cuda_bf16.h: 没有那个文件或目录
         11 | #include <cuda_bf16.h>
            |          ^~~~~~~~~~~~~
      compilation terminated.
      In file included from /usr/include/cuda_runtime.h:83,
                       from <command-line>:
      /usr/include/crt/host_config.h:138:2: error: #error -- unsupported GNU version! gcc versions later than 8 are not supported!
        138 | #error -- unsupported GNU version! gcc versions later than 8 are not supported!
            |  ^~~~~
      In file included from /home/xys/paper_code/VMamba-main/kernels/selective_scan/csrc/selective_scan/cusoflex/selective_scan_bwd_kernel_oflex.cuh:7,
                       from /home/xys/paper_code/VMamba-main/kernels/selective_scan/csrc/selective_scan/cusoflex/selective_scan_core_bwd.cu:4:
      /home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include/c10/util/BFloat16.h:11:10: fatal error: cuda_bf16.h: 没有那个文件或目录
         11 | #include <cuda_bf16.h>
            |          ^~~~~~~~~~~~~
      compilation terminated.
      In file included from /usr/include/cuda_runtime.h:83,
                       from <command-line>:
      /usr/include/crt/host_config.h:138:2: error: #error -- unsupported GNU version! gcc versions later than 8 are not supported!
        138 | #error -- unsupported GNU version! gcc versions later than 8 are not supported!
            |  ^~~~~
      In file included from /home/xys/paper_code/VMamba-main/kernels/selective_scan/csrc/selective_scan/cusoflex/selective_scan_bwd_kernel_oflex.cuh:7,
                       from /home/xys/paper_code/VMamba-main/kernels/selective_scan/csrc/selective_scan/cusoflex/selective_scan_core_bwd.cu:4:
      /home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include/c10/util/BFloat16.h:11:10: fatal error: cuda_bf16.h: 没有那个文件或目录
         11 | #include <cuda_bf16.h>
            |          ^~~~~~~~~~~~~
      compilation terminated.
      In file included from /usr/include/cuda_runtime.h:83,
                       from <command-line>:
      /usr/include/crt/host_config.h:138:2: error: #error -- unsupported GNU version! gcc versions later than 8 are not supported!
        138 | #error -- unsupported GNU version! gcc versions later than 8 are not supported!
            |  ^~~~~
      In file included from /home/xys/paper_code/VMamba-main/kernels/selective_scan/csrc/selective_scan/cusoflex/selective_scan_bwd_kernel_oflex.cuh:7,
                       from /home/xys/paper_code/VMamba-main/kernels/selective_scan/csrc/selective_scan/cusoflex/selective_scan_core_bwd.cu:4:
      /home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include/c10/util/BFloat16.h:11:10: fatal error: cuda_bf16.h: 没有那个文件或目录
         11 | #include <cuda_bf16.h>
            |          ^~~~~~~~~~~~~
      compilation terminated.
      [3/3] c++ -MMD -MF /home/xys/paper_code/VMamba-main/kernels/selective_scan/build/temp.linux-x86_64-cpython-310/csrc/selective_scan/cusoflex/selective_scan_oflex.o.d -pthread -B /home/xys/anaconda3/envs/mamba/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/xys/anaconda3/envs/mamba/include -fPIC -O2 -isystem /home/xys/anaconda3/envs/mamba/include -fPIC -I/home/xys/paper_code/VMamba-main/kernels/selective_scan/csrc/selective_scan -I/home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include -I/home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include/TH -I/home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/include/THC -I/home/xys/anaconda3/envs/mamba/include -I/home/xys/anaconda3/envs/mamba/include/python3.10 -c -c /home/xys/paper_code/VMamba-main/kernels/selective_scan/csrc/selective_scan/cusoflex/selective_scan_oflex.cpp -o /home/xys/paper_code/VMamba-main/kernels/selective_scan/build/temp.linux-x86_64-cpython-310/csrc/selective_scan/cusoflex/selective_scan_oflex.o -O3 -std=c++17 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=selective_scan_cuda_oflex -D_GLIBCXX_USE_CXX11_ABI=0
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2100, in _run_ninja_build
          subprocess.run(
        File "/home/xys/anaconda3/envs/mamba/lib/python3.10/subprocess.py", line 526, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/xys/paper_code/VMamba-main/kernels/selective_scan/setup.py", line 145, in <module>
          setup(
        File "/home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/wheel/_bdist_wheel.py", line 378, in run
          self.run_command("build")
        File "/home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 88, in run
          _build_ext.run(self)
        File "/home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 873, in build_extensions
          build_ext.build_extensions(self)
        File "/home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 249, in build_extension
          _build_ext.build_extension(self, ext)
        File "/home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/Cython/Distutils/build_ext.py", line 135, in build_extension
          super(build_ext, self).build_extension(ext)
        File "/home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
          objects = self.compiler.compile(
        File "/home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 686, in unix_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "/home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1774, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "/home/xys/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2116, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for selective-scan
  Running setup.py clean for selective-scan
Failed to build selective-scan
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (selective-scan)

GPU: single 4090D
CUDA:11.8
torch:2.1.1
python:3.10
pls help me TAT

**Comment by 2326261098** [comment]
我遇到同样的问题，请问解决了吗

**Comment by MzeroMiko** [comment]
It seems like that your cuda library is not compatible with your gcc version. Try updating you cuda version.

**Comment by Imiloin** [comment]
I've encountered the same issue. Using g++ version 11 seems to fix it. Here is what I did:

First install g++-11

```bash
sudo apt install g++-11
```

add the following line to `kernels/selective_scan/setup.py` to explicitly specify the g++ version

```python
def get_ext():
    cc_flag = []

    cc_flag.append("-ccbin=/usr/bin/g++-11")  # add this

    # ...
```

then the setup should work properly with `pip install .`. I suspect this is a compatibility issue with CUDA 11.8.

**Comment by MzeroMiko** [comment]
## 🔥 use VMamba with only ***one file*** and in ***fewest steps*** !
```bash
conda create -n vmamba python=3.10
pip install torch==2.2 torchvision torchaudio triton pytest chardet yacs termcolor fvcore seaborn packaging ninja einops numpy==1.24.4 timm==0.4.12
pip install https://github.com/state-spaces/mamba/releases/download/v2.2.4/mamba_ssm-2.2.4+cu12torch2.2cxx11abiTRUE-cp310-cp310-linux_x86_64.whl
python vmamba.py
```
