### ISSUE TITLE
cd kernels/selective_scan && pip install .      Why does this error occur?

### ISSUE THREAD

**Issue by 2326261098** [MzeroMiko/VMamba#334]
(VMamba) root@autodl-container-3b294fb6e2-9031d1fb:~/autodl-tmp/VMamba/kernels/selective_scan# pip install .
Looking in indexes: http://mirrors.aliyun.com/pypi/simple
Processing /root/autodl-tmp/VMamba/kernels/selective_scan
  Preparing metadata (setup.py) ... done
Requirement already satisfied: torch in /root/miniconda3/envs/VMamba/lib/python3.10/site-packages (from selective_scan==0.0.2) (2.1.1+cu118)
Requirement already satisfied: packaging in /root/miniconda3/envs/VMamba/lib/python3.10/site-packages (from selective_scan==0.0.2) (24.1)
Requirement already satisfied: ninja in /root/miniconda3/envs/VMamba/lib/python3.10/site-packages (from selective_scan==0.0.2) (1.11.1.2)
Requirement already satisfied: einops in /root/miniconda3/envs/VMamba/lib/python3.10/site-packages (from selective_scan==0.0.2) (0.8.0)
Requirement already satisfied: filelock in /root/miniconda3/envs/VMamba/lib/python3.10/site-packages (from torch->selective_scan==0.0.2) (3.13.1)
Requirement already satisfied: typing-extensions in /root/miniconda3/envs/VMamba/lib/python3.10/site-packages (from torch->selective_scan==0.0.2) (4.9.0)
Requirement already satisfied: sympy in /root/miniconda3/envs/VMamba/lib/python3.10/site-packages (from torch->selective_scan==0.0.2) (1.13.1)
Requirement already satisfied: networkx in /root/miniconda3/envs/VMamba/lib/python3.10/site-packages (from torch->selective_scan==0.0.2) (3.2.1)
Requirement already satisfied: jinja2 in /root/miniconda3/envs/VMamba/lib/python3.10/site-packages (from torch->selective_scan==0.0.2) (3.1.3)
Requirement already satisfied: fsspec in /root/miniconda3/envs/VMamba/lib/python3.10/site-packages (from torch->selective_scan==0.0.2) (2024.2.0)
Requirement already satisfied: triton==2.1.0 in /root/miniconda3/envs/VMamba/lib/python3.10/site-packages (from torch->selective_scan==0.0.2) (2.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in /root/miniconda3/envs/VMamba/lib/python3.10/site-packages (from jinja2->torch->selective_scan==0.0.2) (2.1.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /root/miniconda3/envs/VMamba/lib/python3.10/site-packages (from sympy->torch->selective_scan==0.0.2) (1.3.0)
Building wheels for collected packages: selective_scan
  Building wheel for selective_scan (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [107 lines of output]
      
      
      torch.__version__  = 2.1.1+cu118
      
      
      
      
      CUDA_HOME = /root/miniconda3/envs/VMamba
      
      
      CUDA version:  11.8
      running bdist_wheel
      running build
      running build_ext
      /root/miniconda3/envs/VMamba/lib/python3.10/site-packages/torch/utils/cpp_extension.py:424: UserWarning: There are no g++ version bounds defined for CUDA version 11.8
        warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
      building 'selective_scan_cuda_oflex' extension
      creating /root/autodl-tmp/VMamba/kernels/selective_scan/build/temp.linux-x86_64-cpython-310/csrc/selective_scan/cusoflex
      Emitting ninja build file /root/autodl-tmp/VMamba/kernels/selective_scan/build/temp.linux-x86_64-cpython-310/build.ninja...
      Compiling objects...
      Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
      [1/3] c++ -MMD -MF /root/autodl-tmp/VMamba/kernels/selective_scan/build/temp.linux-x86_64-cpython-310/csrc/selective_scan/cusoflex/selective_scan_oflex.o.d -pthread -B /root/miniconda3/envs/VMamba/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /root/miniconda3/envs/VMamba/include -fPIC -O2 -isystem /root/miniconda3/envs/VMamba/include -fPIC -I/root/autodl-tmp/VMamba/kernels/selective_scan/csrc/selective_scan -I/root/miniconda3/envs/VMamba/lib/python3.10/site-packages/torch/include -I/root/miniconda3/envs/VMamba/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/root/miniconda3/envs/VMamba/lib/python3.10/site-packages/torch/include/TH -I/root/miniconda3/envs/VMamba/lib/python3.10/site-packages/torch/include/THC -I/root/miniconda3/envs/VMamba/include -I/root/miniconda3/envs/VMamba/include/python3.10 -c -c /root/autodl-tmp/VMamba/kernels/selective_scan/csrc/selective_scan/cusoflex/selective_scan_oflex.cpp -o /root/autodl-tmp/VMamba/kernels/selective_scan/build/temp.linux-x86_64-cpython-310/csrc/selective_scan/cusoflex/selective_scan_oflex.o -O3 -std=c++17 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=selective_scan_cuda_oflex -D_GLIBCXX_USE_CXX11_ABI=0
      FAILED: /root/autodl-tmp/VMamba/kernels/selective_scan/build/temp.linux-x86_64-cpython-310/csrc/selective_scan/cusoflex/selective_scan_oflex.o
      c++ -MMD -MF /root/autodl-tmp/VMamba/kernels/selective_scan/build/temp.linux-x86_64-cpython-310/csrc/selective_scan/cusoflex/selective_scan_oflex.o.d -pthread -B /root/miniconda3/envs/VMamba/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /root/miniconda3/envs/VMamba/include -fPIC -O2 -isystem /root/miniconda3/envs/VMamba/include -fPIC -I/root/autodl-tmp/VMamba/kernels/selective_scan/csrc/selective_scan -I/root/miniconda3/envs/VMamba/lib/python3.10/site-packages/torch/include -I/root/miniconda3/envs/VMamba/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/root/miniconda3/envs/VMamba/lib/python3.10/site-packages/torch/include/TH -I/root/miniconda3/envs/VMamba/lib/python3.10/site-packages/torch/include/THC -I/root/miniconda3/envs/VMamba/include -I/root/miniconda3/envs/VMamba/include/python3.10 -c -c /root/autodl-tmp/VMamba/kernels/selective_scan/csrc/selective_scan/cusoflex/selective_scan_oflex.cpp -o /root/autodl-tmp/VMamba/kernels/selective_scan/build/temp.linux-x86_64-cpython-310/csrc/selective_scan/cusoflex/selective_scan_oflex.o -O3 -std=c++17 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=selective_scan_cuda_oflex -D_GLIBCXX_USE_CXX11_ABI=0
      In file included from /root/autodl-tmp/VMamba/kernels/selective_scan/csrc/selective_scan/cusoflex/selective_scan_oflex.cpp:5:
      /root/miniconda3/envs/VMamba/lib/python3.10/site-packages/torch/include/ATen/cuda/CUDAContext.h:5:10: fatal error: cuda_runtime_api.h: No such file or directory
          5 | #include <cuda_runtime_api.h>
            |          ^~~~~~~~~~~~~~~~~~~~
      compilation terminated.
      [2/3] /root/miniconda3/envs/VMamba/bin/nvcc  -I/root/autodl-tmp/VMamba/kernels/selective_scan/csrc/selective_scan -I/root/miniconda3/envs/VMamba/lib/python3.10/site-packages/torch/include -I/root/miniconda3/envs/VMamba/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/root/miniconda3/envs/VMamba/lib/python3.10/site-packages/torch/include/TH -I/root/miniconda3/envs/VMamba/lib/python3.10/site-packages/torch/include/THC -I/root/miniconda3/envs/VMamba/include -I/root/miniconda3/envs/VMamba/include/python3.10 -c -c /root/autodl-tmp/VMamba/kernels/selective_scan/csrc/selective_scan/cusoflex/selective_scan_core_bwd.cu -o /root/autodl-tmp/VMamba/kernels/selective_scan/build/temp.linux-x86_64-cpython-310/csrc/selective_scan/cusoflex/selective_scan_core_bwd.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -std=c++17 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_BFLOAT16_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -U__CUDA_NO_BFLOAT162_OPERATORS__ -U__CUDA_NO_BFLOAT162_CONVERSIONS__ --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --ptxas-options=-v -lineinfo -arch=sm_86 --threads 4 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=selective_scan_cuda_oflex -D_GLIBCXX_USE_CXX11_ABI=0
      FAILED: /root/autodl-tmp/VMamba/kernels/selective_scan/build/temp.linux-x86_64-cpython-310/csrc/selective_scan/cusoflex/selective_scan_core_bwd.o
      /root/miniconda3/envs/VMamba/bin/nvcc  -I/root/autodl-tmp/VMamba/kernels/selective_scan/csrc/selective_scan -I/root/miniconda3/envs/VMamba/lib/python3.10/site-packages/torch/include -I/root/miniconda3/envs/VMamba/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/root/miniconda3/envs/VMamba/lib/python3.10/site-packages/torch/include/TH -I/root/miniconda3/envs/VMamba/lib/python3.10/site-packages/torch/include/THC -I/root/miniconda3/envs/VMamba/include -I/root/miniconda3/envs/VMamba/include/python3.10 -c -c /root/autodl-tmp/VMamba/kernels/selective_scan/csrc/selective_scan/cusoflex/selective_scan_core_bwd.cu -o /root/autodl-tmp/VMamba/kernels/selective_scan/build/temp.linux-x86_64-cpython-310/csrc/selective_scan/cusoflex/selective_scan_core_bwd.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -std=c++17 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_BFLOAT16_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -U__CUDA_NO_BFLOAT162_OPERATORS__ -U__CUDA_NO_BFLOAT162_CONVERSIONS__ --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --ptxas-options=-v -lineinfo -arch=sm_86 --threads 4 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=selective_scan_cuda_oflex -D_GLIBCXX_USE_CXX11_ABI=0
      <command-line>: fatal error: cuda_runtime.h: No such file or directory
      compilation terminated.
      <command-line>: fatal error: cuda_runtime.h: No such file or directory
      compilation terminated.
      [3/3] /root/miniconda3/envs/VMamba/bin/nvcc  -I/root/autodl-tmp/VMamba/kernels/selective_scan/csrc/selective_scan -I/root/miniconda3/envs/VMamba/lib/python3.10/site-packages/torch/include -I/root/miniconda3/envs/VMamba/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/root/miniconda3/envs/VMamba/lib/python3.10/site-packages/torch/include/TH -I/root/miniconda3/envs/VMamba/lib/python3.10/site-packages/torch/include/THC -I/root/miniconda3/envs/VMamba/include -I/root/miniconda3/envs/VMamba/include/python3.10 -c -c /root/autodl-tmp/VMamba/kernels/selective_scan/csrc/selective_scan/cusoflex/selective_scan_core_fwd.cu -o /root/autodl-tmp/VMamba/kernels/selective_scan/build/temp.linux-x86_64-cpython-310/csrc/selective_scan/cusoflex/selective_scan_core_fwd.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -std=c++17 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_BFLOAT16_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -U__CUDA_NO_BFLOAT162_OPERATORS__ -U__CUDA_NO_BFLOAT162_CONVERSIONS__ --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --ptxas-options=-v -lineinfo -arch=sm_86 --threads 4 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=selective_scan_cuda_oflex -D_GLIBCXX_USE_CXX11_ABI=0
      FAILED: /root/autodl-tmp/VMamba/kernels/selective_scan/build/temp.linux-x86_64-cpython-310/csrc/selective_scan/cusoflex/selective_scan_core_fwd.o
      /root/miniconda3/envs/VMamba/bin/nvcc  -I/root/autodl-tmp/VMamba/kernels/selective_scan/csrc/selective_scan -I/root/miniconda3/envs/VMamba/lib/python3.10/site-packages/torch/include -I/root/miniconda3/envs/VMamba/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/root/miniconda3/envs/VMamba/lib/python3.10/site-packages/torch/include/TH -I/root/miniconda3/envs/VMamba/lib/python3.10/site-packages/torch/include/THC -I/root/miniconda3/envs/VMamba/include -I/root/miniconda3/envs/VMamba/include/python3.10 -c -c /root/autodl-tmp/VMamba/kernels/selective_scan/csrc/selective_scan/cusoflex/selective_scan_core_fwd.cu -o /root/autodl-tmp/VMamba/kernels/selective_scan/build/temp.linux-x86_64-cpython-310/csrc/selective_scan/cusoflex/selective_scan_core_fwd.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -std=c++17 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_BFLOAT16_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -U__CUDA_NO_BFLOAT162_OPERATORS__ -U__CUDA_NO_BFLOAT162_CONVERSIONS__ --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --ptxas-options=-v -lineinfo -arch=sm_86 --threads 4 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=selective_scan_cuda_oflex -D_GLIBCXX_USE_CXX11_ABI=0
      <command-line>: fatal error: cuda_runtime.h: No such file or directory
      compilation terminated.
      <command-line>: fatal error: cuda_runtime.h: No such file or directory
      compilation terminated.
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/root/miniconda3/envs/VMamba/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2100, in _run_ninja_build
          subprocess.run(
        File "/root/miniconda3/envs/VMamba/lib/python3.10/subprocess.py", line 526, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/root/autodl-tmp/VMamba/kernels/selective_scan/setup.py", line 146, in <module>
          setup(
        File "/root/miniconda3/envs/VMamba/lib/python3.10/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
        File "/root/miniconda3/envs/VMamba/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 183, in setup
          return run_commands(dist)
        File "/root/miniconda3/envs/VMamba/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
          dist.run_commands()
        File "/root/miniconda3/envs/VMamba/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
          self.run_command(cmd)
        File "/root/miniconda3/envs/VMamba/lib/python3.10/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/root/miniconda3/envs/VMamba/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/root/miniconda3/envs/VMamba/lib/python3.10/site-packages/wheel/_bdist_wheel.py", line 378, in run
          self.run_command("build")
        File "/root/miniconda3/envs/VMamba/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/root/miniconda3/envs/VMamba/lib/python3.10/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/root/miniconda3/envs/VMamba/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/root/miniconda3/envs/VMamba/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/root/miniconda3/envs/VMamba/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/root/miniconda3/envs/VMamba/lib/python3.10/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/root/miniconda3/envs/VMamba/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/root/miniconda3/envs/VMamba/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 98, in run
          _build_ext.run(self)
        File "/root/miniconda3/envs/VMamba/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
        File "/root/miniconda3/envs/VMamba/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 873, in build_extensions
          build_ext.build_extensions(self)
        File "/root/miniconda3/envs/VMamba/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 476, in build_extensions
          self._build_extensions_serial()
        File "/root/miniconda3/envs/VMamba/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 502, in _build_extensions_serial
          self.build_extension(ext)
        File "/root/miniconda3/envs/VMamba/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 263, in build_extension
          _build_ext.build_extension(self, ext)
        File "/root/miniconda3/envs/VMamba/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 557, in build_extension
          objects = self.compiler.compile(
        File "/root/miniconda3/envs/VMamba/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 686, in unix_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "/root/miniconda3/envs/VMamba/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1774, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "/root/miniconda3/envs/VMamba/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2116, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for selective_scan
  Running setup.py clean for selective_scan
Failed to build selective_scan
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (selective_scan)

**Comment by 2326261098** [comment]
> 正常情况下，nvcc 不会出现在 conda env 目录中，而是出现在 /usr/local/cuda-?/ 中的 cuda 路径中。
> 
> 我为您安装相应的Linux版本（例如ubuntu）支持的官方源建议存储库（或其镜像）提供的nvidia-drivers，并使用nvidia-official运行文件（安装在/usr/local/）安装cuda库。您安装的 cuda 版本受驱动程序支持，并且与您的 conda env 或 pip env 中安装的两个版本。

感谢回复
