### ISSUE TITLE
_ext.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK3c107SymBool10guard_boolEPKcl

### ISSUE THREAD

**Issue by yuhua666** [MzeroMiko/VMamba#34]
~/VMamba-main/detection# python tools/train.py configs/vssm/mask_rcnn_vssm_fpn_coco_tiny.py
Traceback (most recent call last):
  File "tools/train.py", line 121, in <module>
    main()
  File "tools/train.py", line 110, in main
    runner = Runner.from_cfg(cfg)
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/runner/runner.py", line 462, in from_cfg
    runner = cls(
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/runner/runner.py", line 397, in __init__
    self.log_processor = self.build_log_processor(log_processor)
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1650, in build_log_processor
    log_processor = LOG_PROCESSORS.build(log_processor_cfg)
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 98, in build_from_cfg
    obj_cls = registry.get(obj_type)
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/registry/registry.py", line 451, in get
    self.import_from_location()
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/registry/registry.py", line 376, in import_from_location
    import_module(loc)
  File "/root/miniconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/miniconda3/lib/python3.8/site-packages/mmdet/engine/__init__.py", line 2, in <module>
    from .hooks import *  # noqa: F401, F403
  File "/root/miniconda3/lib/python3.8/site-packages/mmdet/engine/hooks/__init__.py", line 10, in <module>
    from .visualization_hook import (DetVisualizationHook,
  File "/root/miniconda3/lib/python3.8/site-packages/mmdet/engine/hooks/visualization_hook.py", line 14, in <module>
    from mmdet.datasets.samplers import TrackImgSampler
  File "/root/miniconda3/lib/python3.8/site-packages/mmdet/datasets/__init__.py", line 31, in <module>
    from .utils import get_loading_pipeline
  File "/root/miniconda3/lib/python3.8/site-packages/mmdet/datasets/utils.py", line 5, in <module>
    from mmdet.datasets.transforms import LoadAnnotations, LoadPanopticAnnotations
  File "/root/miniconda3/lib/python3.8/site-packages/mmdet/datasets/transforms/__init__.py", line 6, in <module>
    from .formatting import (ImageToTensor, PackDetInputs, PackReIDInputs,
  File "/root/miniconda3/lib/python3.8/site-packages/mmdet/datasets/transforms/formatting.py", line 11, in <module>
    from mmdet.structures.bbox import BaseBoxes
  File "/root/miniconda3/lib/python3.8/site-packages/mmdet/structures/bbox/__init__.py", line 2, in <module>
    from .base_boxes import BaseBoxes
  File "/root/miniconda3/lib/python3.8/site-packages/mmdet/structures/bbox/base_boxes.py", line 9, in <module>
    from mmdet.structures.mask.structures import BitmapMasks, PolygonMasks
  File "/root/miniconda3/lib/python3.8/site-packages/mmdet/structures/mask/__init__.py", line 3, in <module>
    from .structures import (BaseInstanceMasks, BitmapMasks, PolygonMasks,
  File "/root/miniconda3/lib/python3.8/site-packages/mmdet/structures/mask/structures.py", line 12, in <module>
    from mmcv.ops.roi_align import roi_align
  File "/root/miniconda3/lib/python3.8/site-packages/mmcv/ops/__init__.py", line 3, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "/root/miniconda3/lib/python3.8/site-packages/mmcv/ops/active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "/root/miniconda3/lib/python3.8/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/root/miniconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /root/miniconda3/lib/python3.8/site-packages/mmcv/_ext.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK3c107SymBool10guard_boolEPKcl

**Comment by MzeroMiko** [comment]
I think it is because you may have forgotten to build mmcv with extension (`MMCV_WITH_OPS=1`) or installed `mmcv...*.pth` rather than `mmcv-full...*.pth`.  Check [mmcv installation](https://mmcv.readthedocs.io/zh-cn/latest/get_started/installation.html) for details.
