### ISSUE TITLE
NameError: name 'selective_scan_cuda_core' is not defined

### ISSUE THREAD

**Issue by Baobaon** [MzeroMiko/VMamba#76]
It's a really great job, but I'm having a issue.
My error details are as follows:
Traceback (most recent call last):
  File "E:\VMamba-main\classification\models\vmamba.py", line 1196, in <module>
    flops, params = profile(model, (x1, ))
  File "D:\anconda\envs\pytorch2.0\lib\site-packages\thop\profile.py", line 212, in profile
    model(*inputs)
  File "D:\anconda\envs\pytorch2.0\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\VMamba-main\classification\models\vmamba.py", line 1124, in forward
    x = layer(x)
  File "D:\anconda\envs\pytorch2.0\lib\site-packages\torch\nn\modules\module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "D:\anconda\envs\pytorch2.0\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
  File "D:\anconda\envs\pytorch2.0\lib\site-packages\torch\nn\modules\module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "D:\anconda\envs\pytorch2.0\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
  File "D:\anconda\envs\pytorch2.0\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\VMamba-main\classification\models\vmamba.py", line 895, in forward
    return self._forward(input)
  File "E:\VMamba-main\classification\models\vmamba.py", line 883, in _forward
    x = input + self.drop_path(self.op(self.norm(input)))
  File "D:\anconda\envs\pytorch2.0\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\VMamba-main\classification\models\vmamba.py", line 772, in forward
    y = self.forward_core(x, channel_first=with_dconv)
  File "E:\VMamba-main\classification\models\vmamba.py", line 751, in forward_corev2
    x = cross_selective_scan(
  File "E:\VMamba-main\classification\models\vmamba.py", line 440, in cross_selective_scan
    ys: torch.Tensor = selective_scan(
  File "E:\VMamba-main\classification\models\vmamba.py", line 417, in selective_scan
    return SelectiveScan.apply(u, delta, A, B, C, D, delta_bias, delta_softplus, nrows, backnrows, ssoflex)
  File "D:\anconda\envs\pytorch2.0\lib\site-packages\torch\autograd\function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "D:\anconda\envs\pytorch2.0\lib\site-packages\torch\cuda\amp\autocast_mode.py", line 98, in decorate_fwd
    return fwd(*args, **kwargs)
  File "E:\VMamba-main\classification\models\vmamba.py", line 179, in forward
    out, x, *rest = selective_scan_cuda_core.fwd(u, delta, A, B, C, D, delta_bias, delta_softplus, 1)
NameError: name 'selective_scan_cuda_core' is not defined

**Comment by MzeroMiko** [comment]
Actually we do not use selective scan cuda core now， we use selective scan cuda oflex instead, aiming to speed up.

However，both oflex version and core version are supposed to be installed if you installed the selective scan in the folder kernels. 

So have you installed that cuda package?

**Comment by Baobaon** [comment]
> Actually we do not use selective scan cuda core now， we use selective scan cuda oflex instead, aiming to speed up.
> 
> However，both oflex version and core version are supposed to be installed if you installed the selective scan in the folder kernels.
> 
> So have you installed that cuda package?

Thanks for the answer, I'm a newbie to deep learning and my question might confuse you. Pls I want to use selective scan cuda oflex should I download CUDA Toolkit?

**Comment by MzeroMiko** [comment]
Yes. You can follow the steps in README to get started.

**Comment by Baobaon** [comment]
> Yes. You can follow the steps in README to get started.
Thanks for the answer!
But my cuda version is 12.2,  can I not use the selective scan cuda oflex?

**Comment by MzeroMiko** [comment]
Actually, I myself am doing those experiments in cu122+torch2.2+py310 so its ok using cuda 12.2.
Fighting!

**Comment by Baobaon** [comment]
> Actually, I myself am doing those experiments in cu122+torch2.2+py310 so its ok using cuda 12.2. Fighting!
Thank you for your patience in answering, I installed cuda toolkit, But when I use [cd kernels/selective_scan && pip install .] I get the following error：
![Uploading 4D08(39]%UB)6AP[1T6LYOD.png…]()

**Comment by Baobaon** [comment]
> Actually, I myself am doing those experiments in cu122+torch2.2+py310 so its ok using cuda 12.2. Fighting!

Thank you for your patience in answering, I installed cuda toolkit, But when I use [cd kernels/selective_scan && pip install .] I get the following error：
      F:\cuda_do118\include\driver_types.h(82): fatal error C1083: 无法打开包括文件: “stddef.h”: No such file or directory
      error: command 'F:\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX86\\x64\\cl.exe' 
      failed with exit code 2
 
Finally, I have one more question: does VMamba only run on linux systems?

**Comment by MzeroMiko** [comment]
We did not test it on windows. You can refer to issue#26 and try.

By the way. we support mamba_ssm also.

**Comment by 1199answer** [comment]
> Actually, I myself am doing those experiments in cu122+torch2.2+py310 so its ok using cuda 12.2.实际上，我自己正在 cu122+torch2.2+py310 中做这些实验，所以使用 cuda 12.2 是可以的。 Fighting! 战斗！

Boss, what is the corresponding torch version on cuda12.2

**Comment by 1199answer** [comment]
> Actually, I myself am doing those experiments in cu122+torch2.2+py310 so its ok using cuda 12.2.实际上，我自己正在 cu122+torch2.2+py310 中做这些实验，所以使用 cuda 12.2 是可以的。 Fighting! 战斗！

Boss, what is the corresponding torch version on cuda12.2 help help help

**Comment by bryanbocao** [comment]
I tried this
```
~/Repos$ conda activate vmamba
~/Repos/VMamba$ git clone https://github.com/MzeroMiko/VMamba
~/Repos$ cd VMamba
~/Repos/VMamba$ pip install -r requirements.txt
~/Repos/VMamba/kernels/selective_scan$ cd kernels/selective_scan && pip install .
~/Repos/VMamba$ vim kernels/selective_scan/test_selective_scan.py
MODE = "mamba_ssm_sscore" # 1344 items pass
# MODE = "mamba_ssm_sscorendstate" # 1344 items pass
# MODE = "mamba_ssm_ssoflex" # 1344 items pass
```

```
~/Repos/VMamba$ pytest selective_scan/test_selective_scan.py
```
but got
```
================================================ test session starts =================================================platform linux -- Python 3.9.12, pytest-7.1.1, pluggy-1.0.0
rootdir: /home/brcao/Repos/VMamba
plugins: anyio-3.5.0
collected 0 items

=============================================== no tests ran in 0.01s ================================================ERROR: file or directory not found: selective_scan/test_selective_scan.py
```

```
~/Repos/VMamba$ pytest kernels/selective_scan/test_selective_scan.py
================================================ test session starts =================================================platform linux -- Python 3.9.12, pytest-7.1.1, pluggy-1.0.0
rootdir: /home/brcao/Repos/VMamba/kernels/selective_scan
plugins: anyio-3.5.0
collected 0 items / 1 error

======================================================= ERRORS =======================================================______________________________________ ERROR collecting test_selective_scan.py _______________________________________ImportError while importing test module '/home/brcao/Repos/VMamba/kernels/selective_scan/test_selective_scan.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../Apps/anaconda3/envs/vmamba/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
kernels/selective_scan/test_selective_scan.py:341: in <module>
    import selective_scan_cuda_core
```

Any help would be great.

**Comment by 1199answer** [comment]
At that time, selective_stcan could not be installed either, suspecting that the torch and CUDA versions did not match, and CUDA was too high. The official website did not have a standard torch version, and the final version was torch: 2.2.2+CU121; torchaudio：2.2.2+cu121；torchvision:0.17.2+cu121， You can give it a try

**Comment by 1199answer** [comment]
At that time, selective_stcan could not be installed either, suspecting that the torch and CUDA versions did not match, and CUDA was too high. The official website did not have a standard torch version, and the final version was torch: 2.2.2+CU121; torchaudio：2.2.2+cu121；torchvision:0.17.2+cu121， You can give it a try.

**Comment by stc1258** [comment]
> 当时 selective_stcan 也装不上，怀疑火炬和 CUDA 版本不匹配，CUDA 太高。官网没有标准的火炬版本，最终版本是火炬：2.2.2+CU121;torchaudio：2.2.2+cu121;torchvision：0.17.2+cu121，你可以试一试。

哥，[selective_scan]安装成功了，但还是出现NameError: name 'selective_scan_cuda_core' is not defined 这个问题怎么解决

**Comment by isMrSun** [comment]
> > 当时 selective_stcan 也装不上，怀疑火炬和 CUDA 版本不匹配，CUDA 太高。官网没有标准的火炬版本，最终版本是火炬：2.2.2+CU121;torchaudio：2.2.2+cu121;torchvision：0.17.2+cu121，你可以试一试。
> 
> 哥，[selective_scan]安装成功了，但还是出现NameError: name 'selective_scan_cuda_core' is not defined 这个问题怎么解决

在VMamba/kernels/selective_scan/setup.py中找到MODES = ["oflex"]，在MODES = ["oflex"]中添加"core", 这样在执行   pip install .    则会有selective_scan_cuda_core

**Comment by XJWang628** [comment]
> > > 当时 selective_stcan 也装不上，怀疑火炬和 CUDA 版本不匹配，CUDA 太高。官网没有标准的火炬版本，最终版本是火炬：2.2.2+CU121;torchaudio：2.2.2+cu121;torchvision：0.17.2+cu121，你可以试一试。
> > 
> > 
> > 哥，[selective_scan]安装成功了，但还是出现NameError: name 'selective_scan_cuda_core' is not defined 这个问题怎么解决
> 
> 在VMamba/kernels/selective_scan/setup.py中找到MODES = ["oflex"]，在MODES = ["oflex"]中添加"core", 这样在执行 pip install . 则会有selective_scan_cuda_core

确实有用
