### ISSUE TITLE
 RuntimeError: Unknown layout

### ISSUE THREAD

**Issue by dlnn123** [MzeroMiko/VMamba#80]
Hello author, I've encountered this problem:
File "/home/ubuntu/users/leo/VMamba-main/classification/models/vmamba.py", line 332, in forward
    out, x, *rest = selective_scan_cuda_oflex.fwd(u, delta, A, B, C, D, delta_bias, delta_softplus, 1, oflex)
RuntimeError: Unknown layout
[2024-03-10 19:19:03,084] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 14463) of binary: /home/ubuntu/users/leo/miniconda3/envs/vmamba/bin/python
How should I resolve it? Thanks.

**Comment by dlnn123** [comment]
Here are the specific details:
03/10 19:18:56 - mmengine - WARNING - "FileClient" will be deprecated in future. Please use io functions in https://mmengine.readthedocs.io/en/latest/api/fileio.html#file-io
03/10 19:18:56 - mmengine - WARNING - "HardDiskBackend" is the alias of "LocalBackend" and the former will be deprecated in future.
03/10 19:18:56 - mmengine - INFO - Checkpoints will be saved to /home/ubuntu/users/leo/VMamba-main/work_dirs/mask_rcnn_vssm_fpn_coco_tiny.
Traceback (most recent call last):
  File "detection/tools/train.py", line 122, in <module>
    main()
  File "detection/tools/train.py", line 118, in main
    runner.train()
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1777, in train
    model = self.train_loop.run()  # type: ignore
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/mmengine/runner/loops.py", line 96, in run
    self.run_epoch()
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/mmengine/runner/loops.py", line 112, in run_epoch
    self.run_iter(idx, data_batch)
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/mmengine/runner/loops.py", line 128, in run_iter
    outputs = self.runner.model.train_step(
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/mmengine/model/wrappers/distributed.py", line 121, in train_step
    losses = self._run_forward(data, mode='loss')
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/mmengine/model/wrappers/distributed.py", line 161, in _run_forward
    results = self(**data, mode=mode)
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1523, in forward
    else self._run_ddp_forward(*inputs, **kwargs)
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1359, in _run_ddp_forward
    return self.module(*inputs, **kwargs)  # type: ignore[index]
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 92, in forward
    return self.loss(inputs, data_samples)
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/mmdet/models/detectors/two_stage.py", line 160, in loss
    x = self.extract_feat(batch_inputs)
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/mmdet/models/detectors/two_stage.py", line 110, in extract_feat
    x = self.backbone(batch_inputs)
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/users/leo/VMamba-main/classification/models/vmamba.py", line 1483, in forward
    o, x = layer_forward(layer, x) # (B, H, W, C)
  File "/home/ubuntu/users/leo/VMamba-main/classification/models/vmamba.py", line 1476, in layer_forward
    x = l.blocks(x)
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/users/leo/VMamba-main/classification/models/vmamba.py", line 1149, in forward
    return self._forward(input)
  File "/home/ubuntu/users/leo/VMamba-main/classification/models/vmamba.py", line 1137, in _forward
    x = input + self.drop_path(self.op(self.norm(input)))
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/users/leo/VMamba-main/classification/models/vmamba.py", line 913, in forward
    y = self.forward_core(x)
  File "/home/ubuntu/users/leo/VMamba-main/classification/models/vmamba.py", line 888, in forward_corev2
    x = cross_selective_scan(
  File "/home/ubuntu/users/leo/VMamba-main/classification/models/vmamba.py", line 558, in cross_selective_scan
    ys: torch.Tensor = selective_scan(
  File "/home/ubuntu/users/leo/VMamba-main/classification/models/vmamba.py", line 529, in selective_scan
    return SelectiveScan.apply(u, delta, A, B, C, D, delta_bias, delta_softplus, nrows, backnrows, ssoflex)
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/torch/autograd/function.py", line 553, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/torch/cuda/amp/autocast_mode.py", line 115, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/home/ubuntu/users/leo/VMamba-main/classification/models/vmamba.py", line 332, in forward
    out, x, *rest = selective_scan_cuda_oflex.fwd(u, delta, A, B, C, D, delta_bias, delta_softplus, 1, oflex)
RuntimeError: Unknown layout
Traceback (most recent call last):
  File "detection/tools/train.py", line 122, in <module>
    main()
  File "detection/tools/train.py", line 118, in main
    runner.train()
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1777, in train
    model = self.train_loop.run()  # type: ignore
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/mmengine/runner/loops.py", line 96, in run
    self.run_epoch()
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/mmengine/runner/loops.py", line 112, in run_epoch
    self.run_iter(idx, data_batch)
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/mmengine/runner/loops.py", line 128, in run_iter
    outputs = self.runner.model.train_step(
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/mmengine/model/wrappers/distributed.py", line 121, in train_step
    losses = self._run_forward(data, mode='loss')
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/mmengine/model/wrappers/distributed.py", line 161, in _run_forward
    results = self(**data, mode=mode)
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1523, in forward
    else self._run_ddp_forward(*inputs, **kwargs)
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1359, in _run_ddp_forward
    return self.module(*inputs, **kwargs)  # type: ignore[index]
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 92, in forward
    return self.loss(inputs, data_samples)
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/mmdet/models/detectors/two_stage.py", line 160, in loss
    x = self.extract_feat(batch_inputs)
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/mmdet/models/detectors/two_stage.py", line 110, in extract_feat
    x = self.backbone(batch_inputs)
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/users/leo/VMamba-main/classification/models/vmamba.py", line 1483, in forward
    o, x = layer_forward(layer, x) # (B, H, W, C)
  File "/home/ubuntu/users/leo/VMamba-main/classification/models/vmamba.py", line 1476, in layer_forward
    x = l.blocks(x)
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/users/leo/VMamba-main/classification/models/vmamba.py", line 1149, in forward
    return self._forward(input)
  File "/home/ubuntu/users/leo/VMamba-main/classification/models/vmamba.py", line 1137, in _forward
    x = input + self.drop_path(self.op(self.norm(input)))
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/users/leo/VMamba-main/classification/models/vmamba.py", line 913, in forward
    y = self.forward_core(x)
  File "/home/ubuntu/users/leo/VMamba-main/classification/models/vmamba.py", line 888, in forward_corev2
    x = cross_selective_scan(
  File "/home/ubuntu/users/leo/VMamba-main/classification/models/vmamba.py", line 558, in cross_selective_scan
    ys: torch.Tensor = selective_scan(
  File "/home/ubuntu/users/leo/VMamba-main/classification/models/vmamba.py", line 529, in selective_scan
    return SelectiveScan.apply(u, delta, A, B, C, D, delta_bias, delta_softplus, nrows, backnrows, ssoflex)
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/torch/autograd/function.py", line 553, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/torch/cuda/amp/autocast_mode.py", line 115, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/home/ubuntu/users/leo/VMamba-main/classification/models/vmamba.py", line 332, in forward
    out, x, *rest = selective_scan_cuda_oflex.fwd(u, delta, A, B, C, D, delta_bias, delta_softplus, 1, oflex)
RuntimeError: Unknown layout
[2024-03-10 19:19:03,084] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 14463) of binary: /home/ubuntu/users/leo/miniconda3/envs/vmamba/bin/python
Traceback (most recent call last):
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/torch/distributed/launch.py", line 198, in <module>
    main()
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/torch/distributed/launch.py", line 194, in main
    launch(args)
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/torch/distributed/launch.py", line 179, in launch
    run(args)
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/ubuntu/users/leo/miniconda3/envs/vmamba/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
detection/tools/train.py FAILED

**Comment by MzeroMiko** [comment]
Have you tried other version of cuda or pytorch?

**Comment by dlnn123** [comment]
> Have you solved this problem? @dlnn123
yeah,change cuda 10.0 into 11.8, work out it
