### ISSUE TITLE
Error when installing selective_scan

### ISSUE THREAD

**Issue by WqxLoveCoding** [MzeroMiko/VMamba#95]
**Error (same with [#84](https://github.com/MzeroMiko/VMamba/issues/84))：**
![image](https://github.com/MzeroMiko/VMamba/assets/57825815/2bba58c9-327b-4c99-b276-ab41d7cccfd7)

**platform：** `Windows 10`

**pytorch install command (successful)：** `conda install pytorch==2.2.0 torchvision==0.17.0 torchaudio==2.2.0 pytorch-cuda=12.1 -c pytorch -c nvidia`

**python version：** `3.8.18`

**`nvcc -V`** 
![image](https://github.com/MzeroMiko/VMamba/assets/57825815/99e1fb13-ad58-4c0e-95ea-933a462e10aa)

**`nvidia-smi`** 
![image](https://github.com/MzeroMiko/VMamba/assets/57825815/5f8c5eb7-2588-4f77-b939-7fe92d51b724)

**Comment by WqxLoveCoding** [comment]
**Note：** I've found that following the given installation steps on Linux, all steps work fine, so I'm not sure if it's platform related, but I'm currently desperate to experiment on Windows...

**Comment by MzeroMiko** [comment]
M_LOG2E is actually `math_log_2{e}` which is approximately `1.4426950408889634`.  You can `#define M_LOG2E 1.4426950408889634;` to use it.

**Comment by MzeroMiko** [comment]
can you change `constexpr bool` in `static_switch.h` to `static constexpr bool`?

**Comment by WqxLoveCoding** [comment]
> Can you change `constexpr bool` in `static_switch.h` to `static constexpr bool`?
> 
> By the way, you can try changing all `constexpr` to `static constexpr` and install again.

God, it finally worked! Also, the modifications that made the compilation process work are documented here in the hope that they may help others. I'll run training using any of the models to verify that the compilation is okay.

1. Change `constexpr bool` in `kernels/selective_scan/csrc/selective_scan/static_switch.h` to `static const bool`;
2. Add the following code

```
#ifndef M_LOG2E
#define M_LOG2E 1.4426950408889634074
#endif
```

to：

- `kernels/selective_scan/csrc/selective_scan/cus/selective_scan_bwd_kernel.cuh`
- `kernels/selective_scan/csrc/selective_scan/cus/selective_scan_fwd_kernel.cuh`
- `kernels/selective_scan/csrc/selective_scan/cusndstate/selective_scan_bwd_kernel_ndstate.cuh`
- `kernels/selective_scan/csrc/selective_scan/cusndstate/selective_scan_fwd_kernel_ndstate.cuh`
- `kernels/selective_scan/csrc/selective_scan/cusoflex/selective_scan_bwd_kernel_oflex.cuh`
- `kernels/selective_scan/csrc/selective_scan/cusoflex/selective_scan_fwd_kernel_oflex.cuh`

Useful links:

1. This issue
2. [link 1](https://github.com/MzeroMiko/VMamba/issues/52)
3. [link 2](https://github.com/gsgen3d/gsgen/issues/3#issuecomment-1741591484)
4. [link 3](https://github.com/state-spaces/mamba/issues/12)

**Comment by CosmoWood** [comment]
> > Can you change `constexpr bool` in `static_switch.h` to `static constexpr bool`?
> > By the way, you can try changing all `constexpr` to `static constexpr` and install again.
> 
> God, it finally worked! Also, the modifications that made the compilation process work are documented here in the hope that they may help others. I'll run training using any of the models to verify that the compilation is okay.
> 
> 1. Change `constexpr bool` in `kernels/selective_scan/csrc/selective_scan/static_switch.h` to `static const bool`;
> 2. Add the following code
> 
> ```
> #ifndef M_LOG2E
> #define M_LOG2E 1.4426950408889634074
> #endif
> ```
> 
> to：
> 
> * `kernels/selective_scan/csrc/selective_scan/cus/selective_scan_bwd_kernel.cuh`
> * `kernels/selective_scan/csrc/selective_scan/cus/selective_scan_fwd_kernel.cuh`
> * `kernels/selective_scan/csrc/selective_scan/cusndstate/selective_scan_bwd_kernel_ndstate.cuh`
> * `kernels/selective_scan/csrc/selective_scan/cusndstate/selective_scan_fwd_kernel_ndstate.cuh`
> * `kernels/selective_scan/csrc/selective_scan/cusoflex/selective_scan_bwd_kernel_oflex.cuh`
> * `kernels/selective_scan/csrc/selective_scan/cusoflex/selective_scan_fwd_kernel_oflex.cuh`
> 
> Useful links:
> 
> 1. This issue
> 2. [link 1](https://github.com/MzeroMiko/VMamba/issues/52)
> 3. [link 2](https://github.com/gsgen3d/gsgen/issues/3#issuecomment-1741591484)
> 4. [link 3](https://github.com/state-spaces/mamba/issues/12)

It worked Thanks

**Comment by wenqiuL** [comment]
oh my god! Finally solved! Very useful, thank you, successfully installed on Windows. Please provide me with the successful version
![1](https://github.com/user-attachments/assets/b3b2ec7b-1019-4e2d-9af4-52a0c1799b11)
![2](https://github.com/user-attachments/assets/9e29eec2-58fb-4025-9bff-fd38ee9b1fb9)

**Comment by ddcx00** [comment]
> **错误（同[#84](https://github.com/MzeroMiko/VMamba/issues/84)）：** ![图像](https://private-user-images.githubusercontent.com/57825815/313896144-2bba58c9-327b-4c99-b276-ab41d7cccfd7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4ODUzMzksIm5iZiI6MTcyNTg4NTAzOSwicGF0aCI6Ii81NzgyNTgxNS8zMTM4OTYxNDQtMmJiYTU4YzktMzI3Yi00Yzk5LWIyNzYtYWI0MWQ3Y2NjZmQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDEyMzAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhNjhkYjkyZGQzZmMwMDE3YmVmNjM1OWIwYzViYWUzODlmZDNkMDc3M2EwZWFkOWVlY2Q5MDM3ZDgyNWM5ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Th5WVq_wRV5KgXHLSfa5cQ4cct_47w_Hic41f1KJStk)
> 
> **平台：** `Windows 10`
> 
> **pytorch install命令（成功）：** `conda install pytorch==2.2.0 torchvision==0.17.0 torchaudio==2.2.0 pytorch-cuda=12.1 -c pytorch -c nvidia`
> 
> **python版本：** `3.8.18`
> 
> **`nvcc -V`** ![图像](https://private-user-images.githubusercontent.com/57825815/313895672-99e1fb13-ad58-4c0e-95ea-933a462e10aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4ODUzMzksIm5iZiI6MTcyNTg4NTAzOSwicGF0aCI6Ii81NzgyNTgxNS8zMTM4OTU2NzItOTllMWZiMTMtYWQ1OC00YzBlLTk1ZWEtOTMzYTQ2MmUxMGFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDEyMzAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjYjNjZGY5MDRmNGVlMDVhNzljYzdjYTI0NTkxNmVlNjM3YzBiZTAyNzJmYWRkNTVmZDRjMzllYjNiNWM2YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zP-I89ufGPNyE0p1okDKznTBSj8ZgCX61gdbnR-l3HQ)
> 
> **`nvidia-smi`** ![图像](https://private-user-images.githubusercontent.com/57825815/313895760-5f8c5eb7-2588-4f77-b939-7fe92d51b724.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4ODUzMzksIm5iZiI6MTcyNTg4NTAzOSwicGF0aCI6Ii81NzgyNTgxNS8zMTM4OTU3NjAtNWY4YzVlYjctMjU4OC00Zjc3LWI5MzktN2ZlOTJkNTFiNzI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDEyMzAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5OGQ5M2EyMWE0NTlkODhlOWVkODVkN2NiYjgxMmNkNjVhNDM0ZTQyMjVkMjYwMmFjODYzNTU1NzRmYmU5MTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-25kRg6ObW9ldIkf1voLhJATh_0GkTZW9QMvDZc8i7c)



Excuse me? I noticed that the environment you are using is Python 3.8 version，how do I install the Triton library on the Windows platform？

**Comment by Si1ive** [comment]
我C！！！！牛逼

**Comment by RuoYuHY** [comment]
注意: 包含文件:     D:\APP\Miniconda\envs\vmamba\lib\site-packages\torch\include\torch\csrc\api\include\torch/optim/adamw.h
      注意: 包含文件:     D:\APP\Miniconda\envs\vmamba\lib\site-packages\torch\include\torch\csrc\api\include\torch/optim/lbfgs.h
      D:\APP\Miniconda\envs\vmamba\lib\site-packages\torch\include\c10/util/Optional.h(172): warning C4624: “c10::constexpr_storage_t<T>”: 已将析构 函数隐式定义为“已删除”
              with
              [
                  T=std::vector<at::Tensor,std::allocator<at::Tensor>>
              ]
      D:\APP\Miniconda\envs\vmamba\lib\site-packages\torch\include\c10/util/Optional.h(172): note: 模板实例化上下文(最早的实例化上下文)为
      D:\APP\Miniconda\envs\vmamba\lib\site-packages\torch\include\torch\csrc\api\include\torch/optim/lbfgs.h(47): note: 查看对正在编译的 类 模板 实化“c10::optional<std::vector<at::Tensor,std::allocator<at::Tensor>>>”的引用
      D:\APP\Miniconda\envs\vmamba\lib\site-packages\torch\include\c10/util/Optional.h(427): note: 查看对正在编译的 别名 模板 实例化“c10::OptionalBase<T>”的引用
              with
              [
                  T=std::vector<at::Tensor,std::allocator<at::Tensor>>
              ]
      D:\APP\Miniconda\envs\vmamba\lib\site-packages\torch\include\c10/util/Optional.h(408): note: 查看对正在编译的 类 模板 实例化“c10::trivially_copyable_optimization_optional_base<T>”的引用
              with
              [
                  T=std::vector<at::Tensor,std::allocator<at::Tensor>>
              ]
      D:\APP\Miniconda\envs\vmamba\lib\site-packages\torch\include\c10/util/Optional.h(367): note: 查看对正在编译的 类 模板 实例化“c10::constexpr_storage_t<T>”的引用
              with
              [
                  T=std::vector<at::Tensor,std::allocator<at::Tensor>>
              ]
      D:\APP\Miniconda\envs\vmamba\lib\site-packages\torch\include\c10/util/Optional.h(365): warning C4624: “c10::trivially_copyable_optimization_optional_base<T>”: 已将析构函数隐式定义为“已删除”
              with
              [
                  T=std::vector<at::Tensor,std::allocator<at::Tensor>>
              ]
      注意: 包含文件:     D:\APP\Miniconda\envs\vmamba\lib\site-packages\torch\include\torch\csrc\api\include\torch/optim/rmsprop.h
      注意: 包含文件:     D:\APP\Miniconda\envs\vmamba\lib\site-packages\torch\include\torch\csrc\api\include\torch/optim/sgd.h
注意: 包含文件:  D:\Document\PythonProject\VMamba-main\kernels\selective_scan\csrc\selective_scan\cusoflex\selective_scan_oflex.h
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "D:\APP\Miniconda\envs\vmamba\lib\site-packages\torch\utils\cpp_extension.py", line 1666, in _run_ninja_build
          subprocess.run(
        File "D:\APP\Miniconda\envs\vmamba\lib\subprocess.py", line 516, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "D:\Document\PythonProject\VMamba-main\kernels\selective_scan\setup.py", line 146, in <module>
          setup(
 File "D:\APP\Miniconda\envs\vmamba\lib\site-packages\torch\utils\cpp_extension.py", line 1682, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for selective_scan
  Running setup.py clean for selective_scan
Failed to build selective_scan
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (selective_scan)


I tried downloading on windows, what is this error? If I use a lower version of CUDA, will it cause errors?
